/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AccountInfoMeta } from './AccountInfoMeta.js';
import {
    AccountInfoMetaFromJSON,
    AccountInfoMetaFromJSONTyped,
    AccountInfoMetaToJSON,
    AccountInfoMetaToJSONTyped,
} from './AccountInfoMeta.js';
import type { AccountInfoValue } from './AccountInfoValue.js';
import {
    AccountInfoValueFromJSON,
    AccountInfoValueFromJSONTyped,
    AccountInfoValueToJSON,
    AccountInfoValueToJSONTyped,
} from './AccountInfoValue.js';

/**
 * 
 * @export
 * @interface AccountInfoOk
 */
export interface AccountInfoOk {
    /**
     * 
     * @type {string}
     * @memberof AccountInfoOk
     */
    status: AccountInfoOkStatusEnum;
    /**
     * 
     * @type {AccountInfoMeta}
     * @memberof AccountInfoOk
     */
    meta: AccountInfoMeta;
    /**
     * 
     * @type {{ [key: string]: AccountInfoValue | null; }}
     * @memberof AccountInfoOk
     */
    data: { [key: string]: AccountInfoValue | null; };
}


/**
 * @export
 */
export const AccountInfoOkStatusEnum = {
    Ok: 'ok'
} as const;
export type AccountInfoOkStatusEnum = typeof AccountInfoOkStatusEnum[keyof typeof AccountInfoOkStatusEnum];


/**
 * Check if a given object implements the AccountInfoOk interface.
 */
export function instanceOfAccountInfoOk(value: object): value is AccountInfoOk {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AccountInfoOkFromJSON(json: any): AccountInfoOk {
    return AccountInfoOkFromJSONTyped(json, false);
}

export function AccountInfoOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountInfoOk {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'meta': AccountInfoMetaFromJSON(json['meta']),
        'data': (mapValues(json['data'], AccountInfoValueFromJSON)),
    };
}

export function AccountInfoOkToJSON(json: any): AccountInfoOk {
    return AccountInfoOkToJSONTyped(json, false);
}

export function AccountInfoOkToJSONTyped(value?: AccountInfoOk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'meta': AccountInfoMetaToJSON(value['meta']),
        'data': (mapValues(value['data'], AccountInfoValueToJSON)),
    };
}

