/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Account restrictions
 * @export
 * @interface AccountInfoValuePrivateRestrictions
 */
export interface AccountInfoValuePrivateRestrictions {
    /**
     * 
     * @type {number}
     * @memberof AccountInfoValuePrivateRestrictions
     */
    chatBanTime: number | null;
}

/**
 * Check if a given object implements the AccountInfoValuePrivateRestrictions interface.
 */
export function instanceOfAccountInfoValuePrivateRestrictions(value: object): value is AccountInfoValuePrivateRestrictions {
    if (!('chatBanTime' in value) || value['chatBanTime'] === undefined) return false;
    return true;
}

export function AccountInfoValuePrivateRestrictionsFromJSON(json: any): AccountInfoValuePrivateRestrictions {
    return AccountInfoValuePrivateRestrictionsFromJSONTyped(json, false);
}

export function AccountInfoValuePrivateRestrictionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountInfoValuePrivateRestrictions {
    if (json == null) {
        return json;
    }
    return {
        
        'chatBanTime': json['chat_ban_time'],
    };
}

export function AccountInfoValuePrivateRestrictionsToJSON(json: any): AccountInfoValuePrivateRestrictions {
    return AccountInfoValuePrivateRestrictionsToJSONTyped(json, false);
}

export function AccountInfoValuePrivateRestrictionsToJSONTyped(value?: AccountInfoValuePrivateRestrictions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chat_ban_time': value['chatBanTime'],
    };
}

