/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AccountListDataItem
 */
export interface AccountListDataItem {
    /**
     * Player ID
     * @type {number}
     * @memberof AccountListDataItem
     */
    account_id: number;
    /**
     * Player name
     * @type {string}
     * @memberof AccountListDataItem
     */
    nickname: string;
}

/**
 * Check if a given object implements the AccountListDataItem interface.
 */
export function instanceOfAccountListDataItem(value: object): value is AccountListDataItem {
    if (!('account_id' in value) || value['account_id'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    return true;
}

export function AccountListDataItemFromJSON(json: any): AccountListDataItem {
    return AccountListDataItemFromJSONTyped(json, false);
}

export function AccountListDataItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountListDataItem {
    if (json == null) {
        return json;
    }
    return {
        
        'account_id': json['account_id'],
        'nickname': json['nickname'],
    };
}

export function AccountListDataItemToJSON(json: any): AccountListDataItem {
    return AccountListDataItemToJSONTyped(json, false);
}

export function AccountListDataItemToJSONTyped(value?: AccountListDataItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['account_id'],
        'nickname': value['nickname'],
    };
}

export const AccountListDataItemPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

