/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AccountListDataItem } from './AccountListDataItem.js';
import {
    AccountListDataItemFromJSON,
    AccountListDataItemFromJSONTyped,
    AccountListDataItemToJSON,
    AccountListDataItemToJSONTyped,
} from './AccountListDataItem.js';
import type { AccountListMeta } from './AccountListMeta.js';
import {
    AccountListMetaFromJSON,
    AccountListMetaFromJSONTyped,
    AccountListMetaToJSON,
    AccountListMetaToJSONTyped,
} from './AccountListMeta.js';

/**
 * 
 * @export
 * @interface AccountListOk
 */
export interface AccountListOk {
    /**
     * 
     * @type {string}
     * @memberof AccountListOk
     */
    status: AccountListOkStatusEnum;
    /**
     * 
     * @type {AccountListMeta}
     * @memberof AccountListOk
     */
    meta: AccountListMeta;
    /**
     * 
     * @type {Array<AccountListDataItem>}
     * @memberof AccountListOk
     */
    data: Array<AccountListDataItem>;
}

/**
* @export
* @enum {string}
*/
export enum AccountListOkStatusEnum {
    Ok = 'ok'
}


/**
 * Check if a given object implements the AccountListOk interface.
 */
export function instanceOfAccountListOk(value: object): value is AccountListOk {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AccountListOkFromJSON(json: any): AccountListOk {
    return AccountListOkFromJSONTyped(json, false);
}

export function AccountListOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountListOk {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'meta': AccountListMetaFromJSON(json['meta']),
        'data': ((json['data'] as Array<any>).map(AccountListDataItemFromJSON)),
    };
}

export function AccountListOkToJSON(json: any): AccountListOk {
    return AccountListOkToJSONTyped(json, false);
}

export function AccountListOkToJSONTyped(value?: AccountListOk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'meta': AccountListMetaToJSON(value['meta']),
        'data': ((value['data'] as Array<any>).map(AccountListDataItemToJSON)),
    };
}

export const AccountListOkPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

