/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AccountInfoMeta
 */
export interface AccountInfoMeta {
    /**
     * 
     * @type {number}
     * @memberof AccountInfoMeta
     */
    count: number;
}

/**
 * Check if a given object implements the AccountInfoMeta interface.
 */
export function instanceOfAccountInfoMeta(value: object): value is AccountInfoMeta {
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function AccountInfoMetaFromJSON(json: any): AccountInfoMeta {
    return AccountInfoMetaFromJSONTyped(json, false);
}

export function AccountInfoMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountInfoMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
    };
}

export function AccountInfoMetaToJSON(json: any): AccountInfoMeta {
    return AccountInfoMetaToJSONTyped(json, false);
}

export function AccountInfoMetaToJSONTyped(value?: AccountInfoMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
    };
}

export const AccountInfoMetaPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

