/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { StrongholdActivateclanreserveError } from './StrongholdActivateclanreserveError.js';
import {
    instanceOfStrongholdActivateclanreserveError,
    StrongholdActivateclanreserveErrorFromJSON,
    StrongholdActivateclanreserveErrorFromJSONTyped,
    StrongholdActivateclanreserveErrorToJSON,
} from './StrongholdActivateclanreserveError.js';
import type { StrongholdActivateclanreserveOk } from './StrongholdActivateclanreserveOk.js';
import {
    instanceOfStrongholdActivateclanreserveOk,
    StrongholdActivateclanreserveOkFromJSON,
    StrongholdActivateclanreserveOkFromJSONTyped,
    StrongholdActivateclanreserveOkToJSON,
} from './StrongholdActivateclanreserveOk.js';

/**
 * @type Activateclanreserve200Response
 * 
 * @export
 */
export type Activateclanreserve200Response = StrongholdActivateclanreserveError | StrongholdActivateclanreserveOk;

export function Activateclanreserve200ResponseFromJSON(json: any): Activateclanreserve200Response {
    return Activateclanreserve200ResponseFromJSONTyped(json, false);
}

export function Activateclanreserve200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Activateclanreserve200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfStrongholdActivateclanreserveError(json)) {
        return StrongholdActivateclanreserveErrorFromJSONTyped(json, true);
    }
    if (instanceOfStrongholdActivateclanreserveOk(json)) {
        return StrongholdActivateclanreserveOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function Activateclanreserve200ResponseToJSON(json: any): any {
    return Activateclanreserve200ResponseToJSONTyped(json, false);
}

export function Activateclanreserve200ResponseToJSONTyped(value?: Activateclanreserve200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfStrongholdActivateclanreserveError(value)) {
        return StrongholdActivateclanreserveErrorToJSON(value as StrongholdActivateclanreserveError);
    }
    if (instanceOfStrongholdActivateclanreserveOk(value)) {
        return StrongholdActivateclanreserveOkToJSON(value as StrongholdActivateclanreserveOk);
    }

    return {};
}

