/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Authentication error
 * @export
 * @interface AuthLoginErrorErrorOneOf2
 */
export interface AuthLoginErrorErrorOneOf2 {
    /**
     * 
     * @type {number}
     * @memberof AuthLoginErrorErrorOneOf2
     */
    code: AuthLoginErrorErrorOneOf2CodeEnum;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginErrorErrorOneOf2
     */
    message: AuthLoginErrorErrorOneOf2MessageEnum;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginErrorErrorOneOf2
     */
    field: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginErrorErrorOneOf2
     */
    value: string | null;
}


/**
 * @export
 */
export const AuthLoginErrorErrorOneOf2CodeEnum = {
    NUMBER_410: 410
} as const;
export type AuthLoginErrorErrorOneOf2CodeEnum = typeof AuthLoginErrorErrorOneOf2CodeEnum[keyof typeof AuthLoginErrorErrorOneOf2CodeEnum];

/**
 * @export
 */
export const AuthLoginErrorErrorOneOf2MessageEnum = {
    AuthError: 'AUTH_ERROR'
} as const;
export type AuthLoginErrorErrorOneOf2MessageEnum = typeof AuthLoginErrorErrorOneOf2MessageEnum[keyof typeof AuthLoginErrorErrorOneOf2MessageEnum];


/**
 * Check if a given object implements the AuthLoginErrorErrorOneOf2 interface.
 */
export function instanceOfAuthLoginErrorErrorOneOf2(value: object): value is AuthLoginErrorErrorOneOf2 {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AuthLoginErrorErrorOneOf2FromJSON(json: any): AuthLoginErrorErrorOneOf2 {
    return AuthLoginErrorErrorOneOf2FromJSONTyped(json, false);
}

export function AuthLoginErrorErrorOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginErrorErrorOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'field': json['field'],
        'value': json['value'],
    };
}

export function AuthLoginErrorErrorOneOf2ToJSON(json: any): AuthLoginErrorErrorOneOf2 {
    return AuthLoginErrorErrorOneOf2ToJSONTyped(json, false);
}

export function AuthLoginErrorErrorOneOf2ToJSONTyped(value?: AuthLoginErrorErrorOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'field': value['field'],
        'value': value['value'],
    };
}

