/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ClansMessageboardMeta } from './ClansMessageboardMeta.js';
import {
    ClansMessageboardMetaFromJSON,
    ClansMessageboardMetaFromJSONTyped,
    ClansMessageboardMetaToJSON,
    ClansMessageboardMetaToJSONTyped,
} from './ClansMessageboardMeta.js';
import type { ClansMessageboardValueItem } from './ClansMessageboardValueItem.js';
import {
    ClansMessageboardValueItemFromJSON,
    ClansMessageboardValueItemFromJSONTyped,
    ClansMessageboardValueItemToJSON,
    ClansMessageboardValueItemToJSONTyped,
} from './ClansMessageboardValueItem.js';

/**
 * 
 * @export
 * @interface ClansMessageboardOk
 */
export interface ClansMessageboardOk {
    /**
     * 
     * @type {string}
     * @memberof ClansMessageboardOk
     */
    status: ClansMessageboardOkStatusEnum;
    /**
     * 
     * @type {ClansMessageboardMeta}
     * @memberof ClansMessageboardOk
     */
    meta: ClansMessageboardMeta;
    /**
     * 
     * @type {{ [key: string]: Array<ClansMessageboardValueItem>; }}
     * @memberof ClansMessageboardOk
     */
    data: { [key: string]: Array<ClansMessageboardValueItem>; };
}


/**
 * @export
 */
export const ClansMessageboardOkStatusEnum = {
    Ok: 'ok'
} as const;
export type ClansMessageboardOkStatusEnum = typeof ClansMessageboardOkStatusEnum[keyof typeof ClansMessageboardOkStatusEnum];


/**
 * Check if a given object implements the ClansMessageboardOk interface.
 */
export function instanceOfClansMessageboardOk(value: object): value is ClansMessageboardOk {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ClansMessageboardOkFromJSON(json: any): ClansMessageboardOk {
    return ClansMessageboardOkFromJSONTyped(json, false);
}

export function ClansMessageboardOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClansMessageboardOk {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'meta': ClansMessageboardMetaFromJSON(json['meta']),
        'data': json['data'],
    };
}

export function ClansMessageboardOkToJSON(json: any): ClansMessageboardOk {
    return ClansMessageboardOkToJSONTyped(json, false);
}

export function ClansMessageboardOkToJSONTyped(value?: ClansMessageboardOk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'meta': ClansMessageboardMetaToJSON(value['meta']),
        'data': value['data'],
    };
}

