/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ClansMessageboardValueItem
 */
export interface ClansMessageboardValueItem {
    /**
     * Message text
     * @type {string}
     * @memberof ClansMessageboardValueItem
     */
    message: string;
    /**
     * Message creation date
     * @type {number}
     * @memberof ClansMessageboardValueItem
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof ClansMessageboardValueItem
     */
    updatedAt: number | null;
    /**
     * Message author ID
     * @type {number}
     * @memberof ClansMessageboardValueItem
     */
    authorId: number;
    /**
     * ID of a player who has changed the message
     * @type {number}
     * @memberof ClansMessageboardValueItem
     */
    editorId: number;
    /**
     * Indicates if the message has been read
     * @type {boolean}
     * @memberof ClansMessageboardValueItem
     */
    isRead: boolean;
}

/**
 * Check if a given object implements the ClansMessageboardValueItem interface.
 */
export function instanceOfClansMessageboardValueItem(value: object): value is ClansMessageboardValueItem {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('editorId' in value) || value['editorId'] === undefined) return false;
    if (!('isRead' in value) || value['isRead'] === undefined) return false;
    return true;
}

export function ClansMessageboardValueItemFromJSON(json: any): ClansMessageboardValueItem {
    return ClansMessageboardValueItemFromJSONTyped(json, false);
}

export function ClansMessageboardValueItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClansMessageboardValueItem {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'authorId': json['author_id'],
        'editorId': json['editor_id'],
        'isRead': json['is_read'],
    };
}

export function ClansMessageboardValueItemToJSON(json: any): ClansMessageboardValueItem {
    return ClansMessageboardValueItemToJSONTyped(json, false);
}

export function ClansMessageboardValueItemToJSONTyped(value?: ClansMessageboardValueItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'author_id': value['authorId'],
        'editor_id': value['editorId'],
        'is_read': value['isRead'],
    };
}

