/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ClansListDataItem } from './ClansListDataItem.js';
import {
    ClansListDataItemFromJSON,
    ClansListDataItemFromJSONTyped,
    ClansListDataItemToJSON,
    ClansListDataItemToJSONTyped,
} from './ClansListDataItem.js';
import type { ClansListMeta } from './ClansListMeta.js';
import {
    ClansListMetaFromJSON,
    ClansListMetaFromJSONTyped,
    ClansListMetaToJSON,
    ClansListMetaToJSONTyped,
} from './ClansListMeta.js';

/**
 * 
 * @export
 * @interface ClansListOk
 */
export interface ClansListOk {
    /**
     * 
     * @type {string}
     * @memberof ClansListOk
     */
    status: ClansListOkStatusEnum;
    /**
     * 
     * @type {ClansListMeta}
     * @memberof ClansListOk
     */
    meta: ClansListMeta;
    /**
     * 
     * @type {Array<ClansListDataItem>}
     * @memberof ClansListOk
     */
    data: Array<ClansListDataItem>;
}

/**
* @export
* @enum {string}
*/
export enum ClansListOkStatusEnum {
    Ok = 'ok'
}


/**
 * Check if a given object implements the ClansListOk interface.
 */
export function instanceOfClansListOk(value: object): value is ClansListOk {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ClansListOkFromJSON(json: any): ClansListOk {
    return ClansListOkFromJSONTyped(json, false);
}

export function ClansListOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClansListOk {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'meta': ClansListMetaFromJSON(json['meta']),
        'data': ((json['data'] as Array<any>).map(ClansListDataItemFromJSON)),
    };
}

export function ClansListOkToJSON(json: any): ClansListOk {
    return ClansListOkToJSONTyped(json, false);
}

export function ClansListOkToJSONTyped(value?: ClansListOk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'meta': ClansListMetaToJSON(value['meta']),
        'data': ((value['data'] as Array<any>).map(ClansListDataItemToJSON)),
    };
}

export const ClansListOkPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

