/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ClanratingsTopDataItem } from './ClanratingsTopDataItem.js';
import {
    ClanratingsTopDataItemFromJSON,
    ClanratingsTopDataItemFromJSONTyped,
    ClanratingsTopDataItemToJSON,
    ClanratingsTopDataItemToJSONTyped,
} from './ClanratingsTopDataItem.js';
import type { ClanratingsTopMeta } from './ClanratingsTopMeta.js';
import {
    ClanratingsTopMetaFromJSON,
    ClanratingsTopMetaFromJSONTyped,
    ClanratingsTopMetaToJSON,
    ClanratingsTopMetaToJSONTyped,
} from './ClanratingsTopMeta.js';

/**
 * 
 * @export
 * @interface ClanratingsTopOk
 */
export interface ClanratingsTopOk {
    /**
     * 
     * @type {string}
     * @memberof ClanratingsTopOk
     */
    status: ClanratingsTopOkStatusEnum;
    /**
     * 
     * @type {ClanratingsTopMeta}
     * @memberof ClanratingsTopOk
     */
    meta: ClanratingsTopMeta;
    /**
     * 
     * @type {Array<ClanratingsTopDataItem>}
     * @memberof ClanratingsTopOk
     */
    data: Array<ClanratingsTopDataItem>;
}

/**
* @export
* @enum {string}
*/
export enum ClanratingsTopOkStatusEnum {
    Ok = 'ok'
}


/**
 * Check if a given object implements the ClanratingsTopOk interface.
 */
export function instanceOfClanratingsTopOk(value: object): value is ClanratingsTopOk {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ClanratingsTopOkFromJSON(json: any): ClanratingsTopOk {
    return ClanratingsTopOkFromJSONTyped(json, false);
}

export function ClanratingsTopOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClanratingsTopOk {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'meta': ClanratingsTopMetaFromJSON(json['meta']),
        'data': ((json['data'] as Array<any>).map(ClanratingsTopDataItemFromJSON)),
    };
}

export function ClanratingsTopOkToJSON(json: any): ClanratingsTopOk {
    return ClanratingsTopOkToJSONTyped(json, false);
}

export function ClanratingsTopOkToJSONTyped(value?: ClanratingsTopOk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'meta': ClanratingsTopMetaToJSON(value['meta']),
        'data': ((value['data'] as Array<any>).map(ClanratingsTopDataItemToJSON)),
    };
}

export const ClanratingsTopOkPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

