/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ClanratingsTopItemGlobalRatingWeightedAvg } from './ClanratingsTopItemGlobalRatingWeightedAvg.js';
import {
    ClanratingsTopItemGlobalRatingWeightedAvgFromJSON,
    ClanratingsTopItemGlobalRatingWeightedAvgFromJSONTyped,
    ClanratingsTopItemGlobalRatingWeightedAvgToJSON,
    ClanratingsTopItemGlobalRatingWeightedAvgToJSONTyped,
} from './ClanratingsTopItemGlobalRatingWeightedAvg.js';
import type { ClanratingsTopItemFbEloRating6 } from './ClanratingsTopItemFbEloRating6.js';
import {
    ClanratingsTopItemFbEloRating6FromJSON,
    ClanratingsTopItemFbEloRating6FromJSONTyped,
    ClanratingsTopItemFbEloRating6ToJSON,
    ClanratingsTopItemFbEloRating6ToJSONTyped,
} from './ClanratingsTopItemFbEloRating6.js';
import type { ClanratingsTopItemFbEloRating8 } from './ClanratingsTopItemFbEloRating8.js';
import {
    ClanratingsTopItemFbEloRating8FromJSON,
    ClanratingsTopItemFbEloRating8FromJSONTyped,
    ClanratingsTopItemFbEloRating8ToJSON,
    ClanratingsTopItemFbEloRating8ToJSONTyped,
} from './ClanratingsTopItemFbEloRating8.js';
import type { ClanratingsTopItemBattlesCountAvg } from './ClanratingsTopItemBattlesCountAvg.js';
import {
    ClanratingsTopItemBattlesCountAvgFromJSON,
    ClanratingsTopItemBattlesCountAvgFromJSONTyped,
    ClanratingsTopItemBattlesCountAvgToJSON,
    ClanratingsTopItemBattlesCountAvgToJSONTyped,
} from './ClanratingsTopItemBattlesCountAvg.js';
import type { ClanratingsTopItemGmEloRating6 } from './ClanratingsTopItemGmEloRating6.js';
import {
    ClanratingsTopItemGmEloRating6FromJSON,
    ClanratingsTopItemGmEloRating6FromJSONTyped,
    ClanratingsTopItemGmEloRating6ToJSON,
    ClanratingsTopItemGmEloRating6ToJSONTyped,
} from './ClanratingsTopItemGmEloRating6.js';
import type { ClanratingsTopItemFbEloRating10 } from './ClanratingsTopItemFbEloRating10.js';
import {
    ClanratingsTopItemFbEloRating10FromJSON,
    ClanratingsTopItemFbEloRating10FromJSONTyped,
    ClanratingsTopItemFbEloRating10ToJSON,
    ClanratingsTopItemFbEloRating10ToJSONTyped,
} from './ClanratingsTopItemFbEloRating10.js';
import type { ClanratingsTopItemWinsRatioAvg } from './ClanratingsTopItemWinsRatioAvg.js';
import {
    ClanratingsTopItemWinsRatioAvgFromJSON,
    ClanratingsTopItemWinsRatioAvgFromJSONTyped,
    ClanratingsTopItemWinsRatioAvgToJSON,
    ClanratingsTopItemWinsRatioAvgToJSONTyped,
} from './ClanratingsTopItemWinsRatioAvg.js';
import type { ClanratingsTopItemV10lAvg } from './ClanratingsTopItemV10lAvg.js';
import {
    ClanratingsTopItemV10lAvgFromJSON,
    ClanratingsTopItemV10lAvgFromJSONTyped,
    ClanratingsTopItemV10lAvgToJSON,
    ClanratingsTopItemV10lAvgToJSONTyped,
} from './ClanratingsTopItemV10lAvg.js';
import type { ClanratingsTopItemEfficiency } from './ClanratingsTopItemEfficiency.js';
import {
    ClanratingsTopItemEfficiencyFromJSON,
    ClanratingsTopItemEfficiencyFromJSONTyped,
    ClanratingsTopItemEfficiencyToJSON,
    ClanratingsTopItemEfficiencyToJSONTyped,
} from './ClanratingsTopItemEfficiency.js';
import type { ClanratingsTopItemGmEloRating8 } from './ClanratingsTopItemGmEloRating8.js';
import {
    ClanratingsTopItemGmEloRating8FromJSON,
    ClanratingsTopItemGmEloRating8FromJSONTyped,
    ClanratingsTopItemGmEloRating8ToJSON,
    ClanratingsTopItemGmEloRating8ToJSONTyped,
} from './ClanratingsTopItemGmEloRating8.js';
import type { ClanratingsTopItemGmEloRating10 } from './ClanratingsTopItemGmEloRating10.js';
import {
    ClanratingsTopItemGmEloRating10FromJSON,
    ClanratingsTopItemGmEloRating10FromJSONTyped,
    ClanratingsTopItemGmEloRating10ToJSON,
    ClanratingsTopItemGmEloRating10ToJSONTyped,
} from './ClanratingsTopItemGmEloRating10.js';
import type { ClanratingsTopItemGlobalRatingAvg } from './ClanratingsTopItemGlobalRatingAvg.js';
import {
    ClanratingsTopItemGlobalRatingAvgFromJSON,
    ClanratingsTopItemGlobalRatingAvgFromJSONTyped,
    ClanratingsTopItemGlobalRatingAvgToJSON,
    ClanratingsTopItemGlobalRatingAvgToJSONTyped,
} from './ClanratingsTopItemGlobalRatingAvg.js';
import type { ClanratingsTopItemBattlesCountAvgDaily } from './ClanratingsTopItemBattlesCountAvgDaily.js';
import {
    ClanratingsTopItemBattlesCountAvgDailyFromJSON,
    ClanratingsTopItemBattlesCountAvgDailyFromJSONTyped,
    ClanratingsTopItemBattlesCountAvgDailyToJSON,
    ClanratingsTopItemBattlesCountAvgDailyToJSONTyped,
} from './ClanratingsTopItemBattlesCountAvgDaily.js';
import type { ClanratingsTopItemGmEloRating } from './ClanratingsTopItemGmEloRating.js';
import {
    ClanratingsTopItemGmEloRatingFromJSON,
    ClanratingsTopItemGmEloRatingFromJSONTyped,
    ClanratingsTopItemGmEloRatingToJSON,
    ClanratingsTopItemGmEloRatingToJSONTyped,
} from './ClanratingsTopItemGmEloRating.js';
import type { ClanratingsTopItemFbEloRating } from './ClanratingsTopItemFbEloRating.js';
import {
    ClanratingsTopItemFbEloRatingFromJSON,
    ClanratingsTopItemFbEloRatingFromJSONTyped,
    ClanratingsTopItemFbEloRatingToJSON,
    ClanratingsTopItemFbEloRatingToJSONTyped,
} from './ClanratingsTopItemFbEloRating.js';
import type { ClanratingsTopItemRatingFort } from './ClanratingsTopItemRatingFort.js';
import {
    ClanratingsTopItemRatingFortFromJSON,
    ClanratingsTopItemRatingFortFromJSONTyped,
    ClanratingsTopItemRatingFortToJSON,
    ClanratingsTopItemRatingFortToJSONTyped,
} from './ClanratingsTopItemRatingFort.js';

/**
 * 
 * @export
 * @interface ClanratingsTopItem
 */
export interface ClanratingsTopItem {
    /**
     * Clan ID
     * @type {number}
     * @memberof ClanratingsTopItem
     */
    clanId: number;
    /**
     * Clan name
     * @type {string}
     * @memberof ClanratingsTopItem
     */
    clanName: string;
    /**
     * Clan tag
     * @type {string}
     * @memberof ClanratingsTopItem
     */
    clanTag: string;
    /**
     * 
     * @type {ClanratingsTopItemV10lAvg}
     * @memberof ClanratingsTopItem
     */
    v10lAvg: ClanratingsTopItemV10lAvg;
    /**
     * 
     * @type {ClanratingsTopItemBattlesCountAvg}
     * @memberof ClanratingsTopItem
     */
    battlesCountAvg: ClanratingsTopItemBattlesCountAvg;
    /**
     * 
     * @type {ClanratingsTopItemBattlesCountAvgDaily}
     * @memberof ClanratingsTopItem
     */
    battlesCountAvgDaily: ClanratingsTopItemBattlesCountAvgDaily;
    /**
     * 
     * @type {ClanratingsTopItemGlobalRatingAvg}
     * @memberof ClanratingsTopItem
     */
    globalRatingAvg: ClanratingsTopItemGlobalRatingAvg;
    /**
     * 
     * @type {ClanratingsTopItemGlobalRatingWeightedAvg}
     * @memberof ClanratingsTopItem
     */
    globalRatingWeightedAvg: ClanratingsTopItemGlobalRatingWeightedAvg;
    /**
     * 
     * @type {ClanratingsTopItemEfficiency}
     * @memberof ClanratingsTopItem
     */
    efficiency: ClanratingsTopItemEfficiency;
    /**
     * 
     * @type {ClanratingsTopItemWinsRatioAvg}
     * @memberof ClanratingsTopItem
     */
    winsRatioAvg: ClanratingsTopItemWinsRatioAvg;
    /**
     * 
     * @type {ClanratingsTopItemRatingFort}
     * @memberof ClanratingsTopItem
     */
    ratingFort: ClanratingsTopItemRatingFort;
    /**
     * 
     * @type {ClanratingsTopItemFbEloRating}
     * @memberof ClanratingsTopItem
     */
    fbEloRating: ClanratingsTopItemFbEloRating;
    /**
     * 
     * @type {ClanratingsTopItemFbEloRating10}
     * @memberof ClanratingsTopItem
     */
    fbEloRating10: ClanratingsTopItemFbEloRating10;
    /**
     * 
     * @type {ClanratingsTopItemFbEloRating8}
     * @memberof ClanratingsTopItem
     */
    fbEloRating8: ClanratingsTopItemFbEloRating8;
    /**
     * 
     * @type {ClanratingsTopItemFbEloRating6}
     * @memberof ClanratingsTopItem
     */
    fbEloRating6: ClanratingsTopItemFbEloRating6;
    /**
     * 
     * @type {ClanratingsTopItemGmEloRating}
     * @memberof ClanratingsTopItem
     */
    gmEloRating: ClanratingsTopItemGmEloRating;
    /**
     * 
     * @type {ClanratingsTopItemGmEloRating10}
     * @memberof ClanratingsTopItem
     */
    gmEloRating10: ClanratingsTopItemGmEloRating10;
    /**
     * 
     * @type {ClanratingsTopItemGmEloRating8}
     * @memberof ClanratingsTopItem
     */
    gmEloRating8: ClanratingsTopItemGmEloRating8;
    /**
     * 
     * @type {ClanratingsTopItemGmEloRating6}
     * @memberof ClanratingsTopItem
     */
    gmEloRating6: ClanratingsTopItemGmEloRating6;
    /**
     * Reasons why specified rating categories were not calculated. Contains data in "key-value" format, where the key is category name and the value is reason.
     * 
     * Possible reasons:
     * 
     *  * inactivity - Inactivity for 28 days
     *  * newbies_measure - Under 10 members in the clan
     *  * limits - Rank conditions not met
     *  * blocked - Clan blocked
     *  * other - Technical reasons
     * @type {{ [key: string]: string; }}
     * @memberof ClanratingsTopItem
     */
    excludeReasons: { [key: string]: string; };
}

/**
 * Check if a given object implements the ClanratingsTopItem interface.
 */
export function instanceOfClanratingsTopItem(value: object): value is ClanratingsTopItem {
    if (!('clanId' in value) || value['clanId'] === undefined) return false;
    if (!('clanName' in value) || value['clanName'] === undefined) return false;
    if (!('clanTag' in value) || value['clanTag'] === undefined) return false;
    if (!('v10lAvg' in value) || value['v10lAvg'] === undefined) return false;
    if (!('battlesCountAvg' in value) || value['battlesCountAvg'] === undefined) return false;
    if (!('battlesCountAvgDaily' in value) || value['battlesCountAvgDaily'] === undefined) return false;
    if (!('globalRatingAvg' in value) || value['globalRatingAvg'] === undefined) return false;
    if (!('globalRatingWeightedAvg' in value) || value['globalRatingWeightedAvg'] === undefined) return false;
    if (!('efficiency' in value) || value['efficiency'] === undefined) return false;
    if (!('winsRatioAvg' in value) || value['winsRatioAvg'] === undefined) return false;
    if (!('ratingFort' in value) || value['ratingFort'] === undefined) return false;
    if (!('fbEloRating' in value) || value['fbEloRating'] === undefined) return false;
    if (!('fbEloRating10' in value) || value['fbEloRating10'] === undefined) return false;
    if (!('fbEloRating8' in value) || value['fbEloRating8'] === undefined) return false;
    if (!('fbEloRating6' in value) || value['fbEloRating6'] === undefined) return false;
    if (!('gmEloRating' in value) || value['gmEloRating'] === undefined) return false;
    if (!('gmEloRating10' in value) || value['gmEloRating10'] === undefined) return false;
    if (!('gmEloRating8' in value) || value['gmEloRating8'] === undefined) return false;
    if (!('gmEloRating6' in value) || value['gmEloRating6'] === undefined) return false;
    if (!('excludeReasons' in value) || value['excludeReasons'] === undefined) return false;
    return true;
}

export function ClanratingsTopItemFromJSON(json: any): ClanratingsTopItem {
    return ClanratingsTopItemFromJSONTyped(json, false);
}

export function ClanratingsTopItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClanratingsTopItem {
    if (json == null) {
        return json;
    }
    return {
        
        'clanId': json['clan_id'],
        'clanName': json['clan_name'],
        'clanTag': json['clan_tag'],
        'v10lAvg': ClanratingsTopItemV10lAvgFromJSON(json['v10l_avg']),
        'battlesCountAvg': ClanratingsTopItemBattlesCountAvgFromJSON(json['battles_count_avg']),
        'battlesCountAvgDaily': ClanratingsTopItemBattlesCountAvgDailyFromJSON(json['battles_count_avg_daily']),
        'globalRatingAvg': ClanratingsTopItemGlobalRatingAvgFromJSON(json['global_rating_avg']),
        'globalRatingWeightedAvg': ClanratingsTopItemGlobalRatingWeightedAvgFromJSON(json['global_rating_weighted_avg']),
        'efficiency': ClanratingsTopItemEfficiencyFromJSON(json['efficiency']),
        'winsRatioAvg': ClanratingsTopItemWinsRatioAvgFromJSON(json['wins_ratio_avg']),
        'ratingFort': ClanratingsTopItemRatingFortFromJSON(json['rating_fort']),
        'fbEloRating': ClanratingsTopItemFbEloRatingFromJSON(json['fb_elo_rating']),
        'fbEloRating10': ClanratingsTopItemFbEloRating10FromJSON(json['fb_elo_rating_10']),
        'fbEloRating8': ClanratingsTopItemFbEloRating8FromJSON(json['fb_elo_rating_8']),
        'fbEloRating6': ClanratingsTopItemFbEloRating6FromJSON(json['fb_elo_rating_6']),
        'gmEloRating': ClanratingsTopItemGmEloRatingFromJSON(json['gm_elo_rating']),
        'gmEloRating10': ClanratingsTopItemGmEloRating10FromJSON(json['gm_elo_rating_10']),
        'gmEloRating8': ClanratingsTopItemGmEloRating8FromJSON(json['gm_elo_rating_8']),
        'gmEloRating6': ClanratingsTopItemGmEloRating6FromJSON(json['gm_elo_rating_6']),
        'excludeReasons': json['exclude_reasons'],
    };
}

export function ClanratingsTopItemToJSON(json: any): ClanratingsTopItem {
    return ClanratingsTopItemToJSONTyped(json, false);
}

export function ClanratingsTopItemToJSONTyped(value?: ClanratingsTopItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clan_id': value['clanId'],
        'clan_name': value['clanName'],
        'clan_tag': value['clanTag'],
        'v10l_avg': ClanratingsTopItemV10lAvgToJSON(value['v10lAvg']),
        'battles_count_avg': ClanratingsTopItemBattlesCountAvgToJSON(value['battlesCountAvg']),
        'battles_count_avg_daily': ClanratingsTopItemBattlesCountAvgDailyToJSON(value['battlesCountAvgDaily']),
        'global_rating_avg': ClanratingsTopItemGlobalRatingAvgToJSON(value['globalRatingAvg']),
        'global_rating_weighted_avg': ClanratingsTopItemGlobalRatingWeightedAvgToJSON(value['globalRatingWeightedAvg']),
        'efficiency': ClanratingsTopItemEfficiencyToJSON(value['efficiency']),
        'wins_ratio_avg': ClanratingsTopItemWinsRatioAvgToJSON(value['winsRatioAvg']),
        'rating_fort': ClanratingsTopItemRatingFortToJSON(value['ratingFort']),
        'fb_elo_rating': ClanratingsTopItemFbEloRatingToJSON(value['fbEloRating']),
        'fb_elo_rating_10': ClanratingsTopItemFbEloRating10ToJSON(value['fbEloRating10']),
        'fb_elo_rating_8': ClanratingsTopItemFbEloRating8ToJSON(value['fbEloRating8']),
        'fb_elo_rating_6': ClanratingsTopItemFbEloRating6ToJSON(value['fbEloRating6']),
        'gm_elo_rating': ClanratingsTopItemGmEloRatingToJSON(value['gmEloRating']),
        'gm_elo_rating_10': ClanratingsTopItemGmEloRating10ToJSON(value['gmEloRating10']),
        'gm_elo_rating_8': ClanratingsTopItemGmEloRating8ToJSON(value['gmEloRating8']),
        'gm_elo_rating_6': ClanratingsTopItemGmEloRating6ToJSON(value['gmEloRating6']),
        'exclude_reasons': value['excludeReasons'],
    };
}

