/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ClansListItemEmblems } from './ClansListItemEmblems.js';
import {
    ClansListItemEmblemsFromJSON,
    ClansListItemEmblemsFromJSONTyped,
    ClansListItemEmblemsToJSON,
    ClansListItemEmblemsToJSONTyped,
} from './ClansListItemEmblems.js';

/**
 * 
 * @export
 * @interface ClansListItem
 */
export interface ClansListItem {
    /**
     * Clan ID
     * @type {number}
     * @memberof ClansListItem
     */
    clanId: number;
    /**
     * Clan name
     * @type {string}
     * @memberof ClansListItem
     */
    name: string;
    /**
     * Clan tag
     * @type {string}
     * @memberof ClansListItem
     */
    tag: string;
    /**
     * Clan creation date
     * @type {number}
     * @memberof ClansListItem
     */
    createdAt: number;
    /**
     * Clan color in HEX #RRGGBB
     * @type {string}
     * @memberof ClansListItem
     */
    color: string;
    /**
     * Number of clan members
     * @type {number}
     * @memberof ClansListItem
     */
    membersCount: number;
    /**
     * 
     * @type {ClansListItemEmblems}
     * @memberof ClansListItem
     */
    emblems: ClansListItemEmblems;
}

/**
 * Check if a given object implements the ClansListItem interface.
 */
export function instanceOfClansListItem(value: object): value is ClansListItem {
    if (!('clanId' in value) || value['clanId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('membersCount' in value) || value['membersCount'] === undefined) return false;
    if (!('emblems' in value) || value['emblems'] === undefined) return false;
    return true;
}

export function ClansListItemFromJSON(json: any): ClansListItem {
    return ClansListItemFromJSONTyped(json, false);
}

export function ClansListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClansListItem {
    if (json == null) {
        return json;
    }
    return {
        
        'clanId': json['clan_id'],
        'name': json['name'],
        'tag': json['tag'],
        'createdAt': json['created_at'],
        'color': json['color'],
        'membersCount': json['members_count'],
        'emblems': ClansListItemEmblemsFromJSON(json['emblems']),
    };
}

export function ClansListItemToJSON(json: any): ClansListItem {
    return ClansListItemToJSONTyped(json, false);
}

export function ClansListItemToJSONTyped(value?: ClansListItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clan_id': value['clanId'],
        'name': value['name'],
        'tag': value['tag'],
        'created_at': value['createdAt'],
        'color': value['color'],
        'members_count': value['membersCount'],
        'emblems': ClansListItemEmblemsToJSON(value['emblems']),
    };
}

