/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Elo rating on the Global Map in Champion division
 * @export
 * @interface ClanratingsTopDataItemGmEloRating8
 */
export interface ClanratingsTopDataItemGmEloRating8 {
    /**
     * Absolute value
     * @type {number}
     * @memberof ClanratingsTopDataItemGmEloRating8
     */
    value: number;
    /**
     * Position
     * @type {number}
     * @memberof ClanratingsTopDataItemGmEloRating8
     */
    rank: number | null;
    /**
     * Change of position in rating
     * @type {number}
     * @memberof ClanratingsTopDataItemGmEloRating8
     */
    rank_delta: number | null;
}

/**
 * Check if a given object implements the ClanratingsTopDataItemGmEloRating8 interface.
 */
export function instanceOfClanratingsTopDataItemGmEloRating8(value: object): value is ClanratingsTopDataItemGmEloRating8 {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if (!('rank_delta' in value) || value['rank_delta'] === undefined) return false;
    return true;
}

export function ClanratingsTopDataItemGmEloRating8FromJSON(json: any): ClanratingsTopDataItemGmEloRating8 {
    return ClanratingsTopDataItemGmEloRating8FromJSONTyped(json, false);
}

export function ClanratingsTopDataItemGmEloRating8FromJSONTyped(json: any, ignoreDiscriminator: boolean): ClanratingsTopDataItemGmEloRating8 {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'rank': json['rank'],
        'rank_delta': json['rank_delta'],
    };
}

export function ClanratingsTopDataItemGmEloRating8ToJSON(json: any): ClanratingsTopDataItemGmEloRating8 {
    return ClanratingsTopDataItemGmEloRating8ToJSONTyped(json, false);
}

export function ClanratingsTopDataItemGmEloRating8ToJSONTyped(value?: ClanratingsTopDataItemGmEloRating8 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'rank': value['rank'],
        'rank_delta': value['rank_delta'],
    };
}

export const ClanratingsTopDataItemGmEloRating8PropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

