/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Elo rating achieved by the clan on Tier X vehicles in the Stronghold mode
 * @export
 * @interface ClanratingsTopItemFbEloRating10
 */
export interface ClanratingsTopItemFbEloRating10 {
    /**
     * Absolute value
     * @type {number}
     * @memberof ClanratingsTopItemFbEloRating10
     */
    value: number;
    /**
     * 
     * @type {number}
     * @memberof ClanratingsTopItemFbEloRating10
     */
    rank: number | null;
    /**
     * 
     * @type {number}
     * @memberof ClanratingsTopItemFbEloRating10
     */
    rankDelta: number | null;
}

/**
 * Check if a given object implements the ClanratingsTopItemFbEloRating10 interface.
 */
export function instanceOfClanratingsTopItemFbEloRating10(value: object): value is ClanratingsTopItemFbEloRating10 {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if (!('rankDelta' in value) || value['rankDelta'] === undefined) return false;
    return true;
}

export function ClanratingsTopItemFbEloRating10FromJSON(json: any): ClanratingsTopItemFbEloRating10 {
    return ClanratingsTopItemFbEloRating10FromJSONTyped(json, false);
}

export function ClanratingsTopItemFbEloRating10FromJSONTyped(json: any, ignoreDiscriminator: boolean): ClanratingsTopItemFbEloRating10 {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'rank': json['rank'],
        'rankDelta': json['rank_delta'],
    };
}

export function ClanratingsTopItemFbEloRating10ToJSON(json: any): ClanratingsTopItemFbEloRating10 {
    return ClanratingsTopItemFbEloRating10ToJSONTyped(json, false);
}

export function ClanratingsTopItemFbEloRating10ToJSONTyped(value?: ClanratingsTopItemFbEloRating10 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'rank': value['rank'],
        'rank_delta': value['rankDelta'],
    };
}

