/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Information on clan emblems in games and on clan portal
 * @export
 * @interface ClansInfoValueEmblems
 */
export interface ClansInfoValueEmblems {
    /**
     * List of links to 24x24 px emblems
     * @type {{ [key: string]: string; }}
     * @memberof ClansInfoValueEmblems
     */
    x24: { [key: string]: string; };
    /**
     * List of links to 32x32 px emblems
     * @type {{ [key: string]: string; }}
     * @memberof ClansInfoValueEmblems
     */
    x32: { [key: string]: string; };
    /**
     * List of links to 64x64 px emblems
     * @type {{ [key: string]: string; }}
     * @memberof ClansInfoValueEmblems
     */
    x64: { [key: string]: string; };
    /**
     * List of links to 195x195 px emblems
     * @type {{ [key: string]: string; }}
     * @memberof ClansInfoValueEmblems
     */
    x195: { [key: string]: string; };
    /**
     * List of links to 256x256 px emblems
     * @type {{ [key: string]: string; }}
     * @memberof ClansInfoValueEmblems
     */
    x256: { [key: string]: string; };
}

/**
 * Check if a given object implements the ClansInfoValueEmblems interface.
 */
export function instanceOfClansInfoValueEmblems(value: object): value is ClansInfoValueEmblems {
    if (!('x24' in value) || value['x24'] === undefined) return false;
    if (!('x32' in value) || value['x32'] === undefined) return false;
    if (!('x64' in value) || value['x64'] === undefined) return false;
    if (!('x195' in value) || value['x195'] === undefined) return false;
    if (!('x256' in value) || value['x256'] === undefined) return false;
    return true;
}

export function ClansInfoValueEmblemsFromJSON(json: any): ClansInfoValueEmblems {
    return ClansInfoValueEmblemsFromJSONTyped(json, false);
}

export function ClansInfoValueEmblemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClansInfoValueEmblems {
    if (json == null) {
        return json;
    }
    return {
        
        'x24': json['x24'],
        'x32': json['x32'],
        'x64': json['x64'],
        'x195': json['x195'],
        'x256': json['x256'],
    };
}

export function ClansInfoValueEmblemsToJSON(json: any): ClansInfoValueEmblems {
    return ClansInfoValueEmblemsToJSONTyped(json, false);
}

export function ClansInfoValueEmblemsToJSONTyped(value?: ClansInfoValueEmblems | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x24': value['x24'],
        'x32': value['x32'],
        'x64': value['x64'],
        'x195': value['x195'],
        'x256': value['x256'],
    };
}

