/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ClansMessageboardMeta } from './ClansMessageboardMeta.js';
import {
    ClansMessageboardMetaFromJSON,
    ClansMessageboardMetaFromJSONTyped,
    ClansMessageboardMetaToJSON,
    ClansMessageboardMetaToJSONTyped,
} from './ClansMessageboardMeta.js';
import type { ClansMessageboardDataValueItem } from './ClansMessageboardDataValueItem.js';
import {
    ClansMessageboardDataValueItemFromJSON,
    ClansMessageboardDataValueItemFromJSONTyped,
    ClansMessageboardDataValueItemToJSON,
    ClansMessageboardDataValueItemToJSONTyped,
} from './ClansMessageboardDataValueItem.js';

/**
 * 
 * @export
 * @interface ClansMessageboardOk
 */
export interface ClansMessageboardOk {
    /**
     * 
     * @type {string}
     * @memberof ClansMessageboardOk
     */
    status: ClansMessageboardOkStatusEnum;
    /**
     * 
     * @type {ClansMessageboardMeta}
     * @memberof ClansMessageboardOk
     */
    meta: ClansMessageboardMeta;
    /**
     * 
     * @type {{ [key: string]: Array<ClansMessageboardDataValueItem> | undefined; }}
     * @memberof ClansMessageboardOk
     */
    data: { [key: string]: Array<ClansMessageboardDataValueItem> | undefined; };
}

/**
* @export
* @enum {string}
*/
export enum ClansMessageboardOkStatusEnum {
    Ok = 'ok'
}


/**
 * Check if a given object implements the ClansMessageboardOk interface.
 */
export function instanceOfClansMessageboardOk(value: object): value is ClansMessageboardOk {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ClansMessageboardOkFromJSON(json: any): ClansMessageboardOk {
    return ClansMessageboardOkFromJSONTyped(json, false);
}

export function ClansMessageboardOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClansMessageboardOk {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'meta': ClansMessageboardMetaFromJSON(json['meta']),
        'data': json['data'],
    };
}

export function ClansMessageboardOkToJSON(json: any): ClansMessageboardOk {
    return ClansMessageboardOkToJSONTyped(json, false);
}

export function ClansMessageboardOkToJSONTyped(value?: ClansMessageboardOk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'meta': ClansMessageboardMetaToJSON(value['meta']),
        'data': value['data'],
    };
}

export const ClansMessageboardOkPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

