/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface EncyclopediaVehicleprofilesValueItem
 */
export interface EncyclopediaVehicleprofilesValueItem {
    /**
     * Vehicle Configuration ID
     * @type {string}
     * @memberof EncyclopediaVehicleprofilesValueItem
     */
    profileId: string;
    /**
     * Vehicle ID
     * @type {number}
     * @memberof EncyclopediaVehicleprofilesValueItem
     */
    tankId: number;
    /**
     * Standard configuration
     * @type {boolean}
     * @memberof EncyclopediaVehicleprofilesValueItem
     */
    isDefault: boolean;
    /**
     * Cost in credits
     * @type {number}
     * @memberof EncyclopediaVehicleprofilesValueItem
     */
    priceCredit: number;
}

/**
 * Check if a given object implements the EncyclopediaVehicleprofilesValueItem interface.
 */
export function instanceOfEncyclopediaVehicleprofilesValueItem(value: object): value is EncyclopediaVehicleprofilesValueItem {
    if (!('profileId' in value) || value['profileId'] === undefined) return false;
    if (!('tankId' in value) || value['tankId'] === undefined) return false;
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    if (!('priceCredit' in value) || value['priceCredit'] === undefined) return false;
    return true;
}

export function EncyclopediaVehicleprofilesValueItemFromJSON(json: any): EncyclopediaVehicleprofilesValueItem {
    return EncyclopediaVehicleprofilesValueItemFromJSONTyped(json, false);
}

export function EncyclopediaVehicleprofilesValueItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaVehicleprofilesValueItem {
    if (json == null) {
        return json;
    }
    return {
        
        'profileId': json['profile_id'],
        'tankId': json['tank_id'],
        'isDefault': json['is_default'],
        'priceCredit': json['price_credit'],
    };
}

export function EncyclopediaVehicleprofilesValueItemToJSON(json: any): EncyclopediaVehicleprofilesValueItem {
    return EncyclopediaVehicleprofilesValueItemToJSONTyped(json, false);
}

export function EncyclopediaVehicleprofilesValueItemToJSONTyped(value?: EncyclopediaVehicleprofilesValueItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile_id': value['profileId'],
        'tank_id': value['tankId'],
        'is_default': value['isDefault'],
        'price_credit': value['priceCredit'],
    };
}

