/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EncyclopediaAchievementsDataValue } from './EncyclopediaAchievementsDataValue.js';
import {
    EncyclopediaAchievementsDataValueFromJSON,
    EncyclopediaAchievementsDataValueFromJSONTyped,
    EncyclopediaAchievementsDataValueToJSON,
    EncyclopediaAchievementsDataValueToJSONTyped,
} from './EncyclopediaAchievementsDataValue.js';
import type { EncyclopediaAchievementsMeta } from './EncyclopediaAchievementsMeta.js';
import {
    EncyclopediaAchievementsMetaFromJSON,
    EncyclopediaAchievementsMetaFromJSONTyped,
    EncyclopediaAchievementsMetaToJSON,
    EncyclopediaAchievementsMetaToJSONTyped,
} from './EncyclopediaAchievementsMeta.js';

/**
 * 
 * @export
 * @interface EncyclopediaAchievementsOk
 */
export interface EncyclopediaAchievementsOk {
    /**
     * 
     * @type {string}
     * @memberof EncyclopediaAchievementsOk
     */
    status: EncyclopediaAchievementsOkStatusEnum;
    /**
     * 
     * @type {EncyclopediaAchievementsMeta}
     * @memberof EncyclopediaAchievementsOk
     */
    meta: EncyclopediaAchievementsMeta;
    /**
     * 
     * @type {{ [key: string]: EncyclopediaAchievementsDataValue | undefined; }}
     * @memberof EncyclopediaAchievementsOk
     */
    data: { [key: string]: EncyclopediaAchievementsDataValue | undefined; };
}

/**
* @export
* @enum {string}
*/
export enum EncyclopediaAchievementsOkStatusEnum {
    Ok = 'ok'
}


/**
 * Check if a given object implements the EncyclopediaAchievementsOk interface.
 */
export function instanceOfEncyclopediaAchievementsOk(value: object): value is EncyclopediaAchievementsOk {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function EncyclopediaAchievementsOkFromJSON(json: any): EncyclopediaAchievementsOk {
    return EncyclopediaAchievementsOkFromJSONTyped(json, false);
}

export function EncyclopediaAchievementsOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaAchievementsOk {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'meta': EncyclopediaAchievementsMetaFromJSON(json['meta']),
        'data': (mapValues(json['data'], EncyclopediaAchievementsDataValueFromJSON)),
    };
}

export function EncyclopediaAchievementsOkToJSON(json: any): EncyclopediaAchievementsOk {
    return EncyclopediaAchievementsOkToJSONTyped(json, false);
}

export function EncyclopediaAchievementsOkToJSONTyped(value?: EncyclopediaAchievementsOk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'meta': EncyclopediaAchievementsMetaToJSON(value['meta']),
        'data': (mapValues(value['data'], EncyclopediaAchievementsDataValueToJSON)),
    };
}

export const EncyclopediaAchievementsOkPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

