/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EncyclopediaBoostersMeta } from './EncyclopediaBoostersMeta.js';
import {
    EncyclopediaBoostersMetaFromJSON,
    EncyclopediaBoostersMetaFromJSONTyped,
    EncyclopediaBoostersMetaToJSON,
    EncyclopediaBoostersMetaToJSONTyped,
} from './EncyclopediaBoostersMeta.js';
import type { EncyclopediaBoostersDataValue } from './EncyclopediaBoostersDataValue.js';
import {
    EncyclopediaBoostersDataValueFromJSON,
    EncyclopediaBoostersDataValueFromJSONTyped,
    EncyclopediaBoostersDataValueToJSON,
    EncyclopediaBoostersDataValueToJSONTyped,
} from './EncyclopediaBoostersDataValue.js';

/**
 * 
 * @export
 * @interface EncyclopediaBoostersOk
 */
export interface EncyclopediaBoostersOk {
    /**
     * 
     * @type {string}
     * @memberof EncyclopediaBoostersOk
     */
    status: EncyclopediaBoostersOkStatusEnum;
    /**
     * 
     * @type {EncyclopediaBoostersMeta}
     * @memberof EncyclopediaBoostersOk
     */
    meta: EncyclopediaBoostersMeta;
    /**
     * 
     * @type {{ [key: string]: EncyclopediaBoostersDataValue | undefined; }}
     * @memberof EncyclopediaBoostersOk
     */
    data: { [key: string]: EncyclopediaBoostersDataValue | undefined; };
}

/**
* @export
* @enum {string}
*/
export enum EncyclopediaBoostersOkStatusEnum {
    Ok = 'ok'
}


/**
 * Check if a given object implements the EncyclopediaBoostersOk interface.
 */
export function instanceOfEncyclopediaBoostersOk(value: object): value is EncyclopediaBoostersOk {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function EncyclopediaBoostersOkFromJSON(json: any): EncyclopediaBoostersOk {
    return EncyclopediaBoostersOkFromJSONTyped(json, false);
}

export function EncyclopediaBoostersOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaBoostersOk {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'meta': EncyclopediaBoostersMetaFromJSON(json['meta']),
        'data': (mapValues(json['data'], EncyclopediaBoostersDataValueFromJSON)),
    };
}

export function EncyclopediaBoostersOkToJSON(json: any): EncyclopediaBoostersOk {
    return EncyclopediaBoostersOkToJSONTyped(json, false);
}

export function EncyclopediaBoostersOkToJSONTyped(value?: EncyclopediaBoostersOk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'meta': EncyclopediaBoostersMetaToJSON(value['meta']),
        'data': (mapValues(value['data'], EncyclopediaBoostersDataValueToJSON)),
    };
}

export const EncyclopediaBoostersOkPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

