/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EncyclopediaArenasError } from './EncyclopediaArenasError.js';
import {
    instanceOfEncyclopediaArenasError,
    EncyclopediaArenasErrorFromJSON,
    EncyclopediaArenasErrorFromJSONTyped,
    EncyclopediaArenasErrorToJSON,
} from './EncyclopediaArenasError.js';
import type { EncyclopediaArenasOk } from './EncyclopediaArenasOk.js';
import {
    instanceOfEncyclopediaArenasOk,
    EncyclopediaArenasOkFromJSON,
    EncyclopediaArenasOkFromJSONTyped,
    EncyclopediaArenasOkToJSON,
} from './EncyclopediaArenasOk.js';

/**
 * @type EncyclopediaArenasResponse
 * 
 * @export
 */
export type EncyclopediaArenasResponse = EncyclopediaArenasError | EncyclopediaArenasOk;

export function EncyclopediaArenasResponseFromJSON(json: any): EncyclopediaArenasResponse {
    return EncyclopediaArenasResponseFromJSONTyped(json, false);
}

export function EncyclopediaArenasResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaArenasResponse {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEncyclopediaArenasError(json)) {
        return EncyclopediaArenasErrorFromJSONTyped(json, true);
    }
    if (instanceOfEncyclopediaArenasOk(json)) {
        return EncyclopediaArenasOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function EncyclopediaArenasResponseToJSON(json: any): any {
    return EncyclopediaArenasResponseToJSONTyped(json, false);
}

export function EncyclopediaArenasResponseToJSONTyped(value?: EncyclopediaArenasResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEncyclopediaArenasError(value)) {
        return EncyclopediaArenasErrorToJSON(value as EncyclopediaArenasError);
    }
    if (instanceOfEncyclopediaArenasOk(value)) {
        return EncyclopediaArenasOkToJSON(value as EncyclopediaArenasOk);
    }

    return {};
}

