/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EncyclopediaCrewskillsMeta } from './EncyclopediaCrewskillsMeta.js';
import {
    EncyclopediaCrewskillsMetaFromJSON,
    EncyclopediaCrewskillsMetaFromJSONTyped,
    EncyclopediaCrewskillsMetaToJSON,
    EncyclopediaCrewskillsMetaToJSONTyped,
} from './EncyclopediaCrewskillsMeta.js';
import type { EncyclopediaCrewskillsValue } from './EncyclopediaCrewskillsValue.js';
import {
    EncyclopediaCrewskillsValueFromJSON,
    EncyclopediaCrewskillsValueFromJSONTyped,
    EncyclopediaCrewskillsValueToJSON,
    EncyclopediaCrewskillsValueToJSONTyped,
} from './EncyclopediaCrewskillsValue.js';

/**
 * 
 * @export
 * @interface EncyclopediaCrewskillsOk
 */
export interface EncyclopediaCrewskillsOk {
    /**
     * 
     * @type {string}
     * @memberof EncyclopediaCrewskillsOk
     */
    status: EncyclopediaCrewskillsOkStatusEnum;
    /**
     * 
     * @type {EncyclopediaCrewskillsMeta}
     * @memberof EncyclopediaCrewskillsOk
     */
    meta: EncyclopediaCrewskillsMeta;
    /**
     * 
     * @type {{ [key: string]: EncyclopediaCrewskillsValue | null; }}
     * @memberof EncyclopediaCrewskillsOk
     */
    data: { [key: string]: EncyclopediaCrewskillsValue | null; };
}


/**
 * @export
 */
export const EncyclopediaCrewskillsOkStatusEnum = {
    Ok: 'ok'
} as const;
export type EncyclopediaCrewskillsOkStatusEnum = typeof EncyclopediaCrewskillsOkStatusEnum[keyof typeof EncyclopediaCrewskillsOkStatusEnum];


/**
 * Check if a given object implements the EncyclopediaCrewskillsOk interface.
 */
export function instanceOfEncyclopediaCrewskillsOk(value: object): value is EncyclopediaCrewskillsOk {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function EncyclopediaCrewskillsOkFromJSON(json: any): EncyclopediaCrewskillsOk {
    return EncyclopediaCrewskillsOkFromJSONTyped(json, false);
}

export function EncyclopediaCrewskillsOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaCrewskillsOk {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'meta': EncyclopediaCrewskillsMetaFromJSON(json['meta']),
        'data': (mapValues(json['data'], EncyclopediaCrewskillsValueFromJSON)),
    };
}

export function EncyclopediaCrewskillsOkToJSON(json: any): EncyclopediaCrewskillsOk {
    return EncyclopediaCrewskillsOkToJSONTyped(json, false);
}

export function EncyclopediaCrewskillsOkToJSONTyped(value?: EncyclopediaCrewskillsOk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'meta': EncyclopediaCrewskillsMetaToJSON(value['meta']),
        'data': (mapValues(value['data'], EncyclopediaCrewskillsValueToJSON)),
    };
}

