/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EncyclopediaCrewrolesError } from './EncyclopediaCrewrolesError.js';
import {
    instanceOfEncyclopediaCrewrolesError,
    EncyclopediaCrewrolesErrorFromJSON,
    EncyclopediaCrewrolesErrorFromJSONTyped,
    EncyclopediaCrewrolesErrorToJSON,
} from './EncyclopediaCrewrolesError.js';
import type { EncyclopediaCrewrolesOk } from './EncyclopediaCrewrolesOk.js';
import {
    instanceOfEncyclopediaCrewrolesOk,
    EncyclopediaCrewrolesOkFromJSON,
    EncyclopediaCrewrolesOkFromJSONTyped,
    EncyclopediaCrewrolesOkToJSON,
} from './EncyclopediaCrewrolesOk.js';

/**
 * @type EncyclopediaCrewrolesResponse
 * 
 * @export
 */
export type EncyclopediaCrewrolesResponse = EncyclopediaCrewrolesError | EncyclopediaCrewrolesOk;

export function EncyclopediaCrewrolesResponseFromJSON(json: any): EncyclopediaCrewrolesResponse {
    return EncyclopediaCrewrolesResponseFromJSONTyped(json, false);
}

export function EncyclopediaCrewrolesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaCrewrolesResponse {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEncyclopediaCrewrolesError(json)) {
        return EncyclopediaCrewrolesErrorFromJSONTyped(json, true);
    }
    if (instanceOfEncyclopediaCrewrolesOk(json)) {
        return EncyclopediaCrewrolesOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function EncyclopediaCrewrolesResponseToJSON(json: any): any {
    return EncyclopediaCrewrolesResponseToJSONTyped(json, false);
}

export function EncyclopediaCrewrolesResponseToJSONTyped(value?: EncyclopediaCrewrolesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEncyclopediaCrewrolesError(value)) {
        return EncyclopediaCrewrolesErrorToJSON(value as EncyclopediaCrewrolesError);
    }
    if (instanceOfEncyclopediaCrewrolesOk(value)) {
        return EncyclopediaCrewrolesOkToJSON(value as EncyclopediaCrewrolesOk);
    }

    return {};
}

