/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EncyclopediaVehicleprofileValueAmmoItemStun } from './EncyclopediaVehicleprofileValueAmmoItemStun.js';
import {
    EncyclopediaVehicleprofileValueAmmoItemStunFromJSON,
    EncyclopediaVehicleprofileValueAmmoItemStunFromJSONTyped,
    EncyclopediaVehicleprofileValueAmmoItemStunToJSON,
    EncyclopediaVehicleprofileValueAmmoItemStunToJSONTyped,
} from './EncyclopediaVehicleprofileValueAmmoItemStun.js';

/**
 * 
 * @export
 * @interface EncyclopediaVehicleprofileValueAmmoItem
 */
export interface EncyclopediaVehicleprofileValueAmmoItem {
    /**
     * Shell type
     * @type {string}
     * @memberof EncyclopediaVehicleprofileValueAmmoItem
     */
    type: string;
    /**
     * Damage (hp), a list of values: min, avg, max
     * @type {Array<number>}
     * @memberof EncyclopediaVehicleprofileValueAmmoItem
     */
    damage: Array<number>;
    /**
     * Penetration (mm), a list of values: min, avg, max
     * @type {Array<number>}
     * @memberof EncyclopediaVehicleprofileValueAmmoItem
     */
    penetration: Array<number>;
    /**
     * 
     * @type {EncyclopediaVehicleprofileValueAmmoItemStun}
     * @memberof EncyclopediaVehicleprofileValueAmmoItem
     */
    stun: EncyclopediaVehicleprofileValueAmmoItemStun | null;
}

/**
 * Check if a given object implements the EncyclopediaVehicleprofileValueAmmoItem interface.
 */
export function instanceOfEncyclopediaVehicleprofileValueAmmoItem(value: object): value is EncyclopediaVehicleprofileValueAmmoItem {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('damage' in value) || value['damage'] === undefined) return false;
    if (!('penetration' in value) || value['penetration'] === undefined) return false;
    if (!('stun' in value) || value['stun'] === undefined) return false;
    return true;
}

export function EncyclopediaVehicleprofileValueAmmoItemFromJSON(json: any): EncyclopediaVehicleprofileValueAmmoItem {
    return EncyclopediaVehicleprofileValueAmmoItemFromJSONTyped(json, false);
}

export function EncyclopediaVehicleprofileValueAmmoItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaVehicleprofileValueAmmoItem {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'damage': json['damage'],
        'penetration': json['penetration'],
        'stun': EncyclopediaVehicleprofileValueAmmoItemStunFromJSON(json['stun']),
    };
}

export function EncyclopediaVehicleprofileValueAmmoItemToJSON(json: any): EncyclopediaVehicleprofileValueAmmoItem {
    return EncyclopediaVehicleprofileValueAmmoItemToJSONTyped(json, false);
}

export function EncyclopediaVehicleprofileValueAmmoItemToJSONTyped(value?: EncyclopediaVehicleprofileValueAmmoItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'damage': value['damage'],
        'penetration': value['penetration'],
        'stun': EncyclopediaVehicleprofileValueAmmoItemStunToJSON(value['stun']),
    };
}

