/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Image links
 * @export
 * @interface EncyclopediaVehiclesValueImages
 */
export interface EncyclopediaVehiclesValueImages {
    /**
     * URL to 160 x 100 px image of vehicle
     * @type {string}
     * @memberof EncyclopediaVehiclesValueImages
     */
    bigIcon: string;
    /**
     * URL to 124 x 31 px image of vehicle
     * @type {string}
     * @memberof EncyclopediaVehiclesValueImages
     */
    smallIcon: string;
    /**
     * URL to outline image of vehicle
     * @type {string}
     * @memberof EncyclopediaVehiclesValueImages
     */
    contourIcon: string;
}

/**
 * Check if a given object implements the EncyclopediaVehiclesValueImages interface.
 */
export function instanceOfEncyclopediaVehiclesValueImages(value: object): value is EncyclopediaVehiclesValueImages {
    if (!('bigIcon' in value) || value['bigIcon'] === undefined) return false;
    if (!('smallIcon' in value) || value['smallIcon'] === undefined) return false;
    if (!('contourIcon' in value) || value['contourIcon'] === undefined) return false;
    return true;
}

export function EncyclopediaVehiclesValueImagesFromJSON(json: any): EncyclopediaVehiclesValueImages {
    return EncyclopediaVehiclesValueImagesFromJSONTyped(json, false);
}

export function EncyclopediaVehiclesValueImagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaVehiclesValueImages {
    if (json == null) {
        return json;
    }
    return {
        
        'bigIcon': json['big_icon'],
        'smallIcon': json['small_icon'],
        'contourIcon': json['contour_icon'],
    };
}

export function EncyclopediaVehiclesValueImagesToJSON(json: any): EncyclopediaVehiclesValueImages {
    return EncyclopediaVehiclesValueImagesToJSONTyped(json, false);
}

export function EncyclopediaVehiclesValueImagesToJSONTyped(value?: EncyclopediaVehiclesValueImages | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'big_icon': value['bigIcon'],
        'small_icon': value['smallIcon'],
        'contour_icon': value['contourIcon'],
    };
}

