/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Suspension characteristics
 * @export
 * @interface EncyclopediaVehiclesDataValueDefaultProfileSuspension
 */
export interface EncyclopediaVehiclesDataValueDefaultProfileSuspension {
    /**
     * Tier
     * @type {number}
     * @memberof EncyclopediaVehiclesDataValueDefaultProfileSuspension
     */
    tier: number;
    /**
     * Module name
     * @type {string}
     * @memberof EncyclopediaVehiclesDataValueDefaultProfileSuspension
     */
    name: string;
    /**
     * Weight (kg)
     * @type {number}
     * @memberof EncyclopediaVehiclesDataValueDefaultProfileSuspension
     */
    weight: number;
    /**
     * Module tag
     * @type {string}
     * @memberof EncyclopediaVehiclesDataValueDefaultProfileSuspension
     */
    tag: string;
    /**
     * Load limit (kg)
     * @type {number}
     * @memberof EncyclopediaVehiclesDataValueDefaultProfileSuspension
     */
    load_limit: number;
    /**
     * Traverse speed (deg/s)
     * @type {number}
     * @memberof EncyclopediaVehiclesDataValueDefaultProfileSuspension
     */
    traverse_speed: number;
    /**
     * Maximum wheel turning angle (for wheeled vehicles)
     * @type {number}
     * @memberof EncyclopediaVehiclesDataValueDefaultProfileSuspension
     */
    steering_lock_angle: number;
}

/**
 * Check if a given object implements the EncyclopediaVehiclesDataValueDefaultProfileSuspension interface.
 */
export function instanceOfEncyclopediaVehiclesDataValueDefaultProfileSuspension(value: object): value is EncyclopediaVehiclesDataValueDefaultProfileSuspension {
    if (!('tier' in value) || value['tier'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('load_limit' in value) || value['load_limit'] === undefined) return false;
    if (!('traverse_speed' in value) || value['traverse_speed'] === undefined) return false;
    if (!('steering_lock_angle' in value) || value['steering_lock_angle'] === undefined) return false;
    return true;
}

export function EncyclopediaVehiclesDataValueDefaultProfileSuspensionFromJSON(json: any): EncyclopediaVehiclesDataValueDefaultProfileSuspension {
    return EncyclopediaVehiclesDataValueDefaultProfileSuspensionFromJSONTyped(json, false);
}

export function EncyclopediaVehiclesDataValueDefaultProfileSuspensionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaVehiclesDataValueDefaultProfileSuspension {
    if (json == null) {
        return json;
    }
    return {
        
        'tier': json['tier'],
        'name': json['name'],
        'weight': json['weight'],
        'tag': json['tag'],
        'load_limit': json['load_limit'],
        'traverse_speed': json['traverse_speed'],
        'steering_lock_angle': json['steering_lock_angle'],
    };
}

export function EncyclopediaVehiclesDataValueDefaultProfileSuspensionToJSON(json: any): EncyclopediaVehiclesDataValueDefaultProfileSuspension {
    return EncyclopediaVehiclesDataValueDefaultProfileSuspensionToJSONTyped(json, false);
}

export function EncyclopediaVehiclesDataValueDefaultProfileSuspensionToJSONTyped(value?: EncyclopediaVehiclesDataValueDefaultProfileSuspension | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tier': value['tier'],
        'name': value['name'],
        'weight': value['weight'],
        'tag': value['tag'],
        'load_limit': value['load_limit'],
        'traverse_speed': value['traverse_speed'],
        'steering_lock_angle': value['steering_lock_angle'],
    };
}

export const EncyclopediaVehiclesDataValueDefaultProfileSuspensionPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

