/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Engine characteristics
 * @export
 * @interface EncyclopediaModulesValueDefaultProfileEngine
 */
export interface EncyclopediaModulesValueDefaultProfileEngine {
    /**
     * Engine Power (hp)
     * @type {number}
     * @memberof EncyclopediaModulesValueDefaultProfileEngine
     */
    power: number;
    /**
     * Chance of engine fire
     * @type {number}
     * @memberof EncyclopediaModulesValueDefaultProfileEngine
     */
    fireChance: number;
}

/**
 * Check if a given object implements the EncyclopediaModulesValueDefaultProfileEngine interface.
 */
export function instanceOfEncyclopediaModulesValueDefaultProfileEngine(value: object): value is EncyclopediaModulesValueDefaultProfileEngine {
    if (!('power' in value) || value['power'] === undefined) return false;
    if (!('fireChance' in value) || value['fireChance'] === undefined) return false;
    return true;
}

export function EncyclopediaModulesValueDefaultProfileEngineFromJSON(json: any): EncyclopediaModulesValueDefaultProfileEngine {
    return EncyclopediaModulesValueDefaultProfileEngineFromJSONTyped(json, false);
}

export function EncyclopediaModulesValueDefaultProfileEngineFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaModulesValueDefaultProfileEngine {
    if (json == null) {
        return json;
    }
    return {
        
        'power': json['power'],
        'fireChance': json['fire_chance'],
    };
}

export function EncyclopediaModulesValueDefaultProfileEngineToJSON(json: any): EncyclopediaModulesValueDefaultProfileEngine {
    return EncyclopediaModulesValueDefaultProfileEngineToJSONTyped(json, false);
}

export function EncyclopediaModulesValueDefaultProfileEngineToJSONTyped(value?: EncyclopediaModulesValueDefaultProfileEngine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'power': value['power'],
        'fire_chance': value['fireChance'],
    };
}

