/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EncyclopediaModulesValueDefaultProfileRadio } from './EncyclopediaModulesValueDefaultProfileRadio.js';
import {
    EncyclopediaModulesValueDefaultProfileRadioFromJSON,
    EncyclopediaModulesValueDefaultProfileRadioFromJSONTyped,
    EncyclopediaModulesValueDefaultProfileRadioToJSON,
    EncyclopediaModulesValueDefaultProfileRadioToJSONTyped,
} from './EncyclopediaModulesValueDefaultProfileRadio.js';
import type { EncyclopediaModulesValueDefaultProfileGun } from './EncyclopediaModulesValueDefaultProfileGun.js';
import {
    EncyclopediaModulesValueDefaultProfileGunFromJSON,
    EncyclopediaModulesValueDefaultProfileGunFromJSONTyped,
    EncyclopediaModulesValueDefaultProfileGunToJSON,
    EncyclopediaModulesValueDefaultProfileGunToJSONTyped,
} from './EncyclopediaModulesValueDefaultProfileGun.js';
import type { EncyclopediaModulesValueDefaultProfileEngine } from './EncyclopediaModulesValueDefaultProfileEngine.js';
import {
    EncyclopediaModulesValueDefaultProfileEngineFromJSON,
    EncyclopediaModulesValueDefaultProfileEngineFromJSONTyped,
    EncyclopediaModulesValueDefaultProfileEngineToJSON,
    EncyclopediaModulesValueDefaultProfileEngineToJSONTyped,
} from './EncyclopediaModulesValueDefaultProfileEngine.js';
import type { EncyclopediaModulesValueDefaultProfileSuspension } from './EncyclopediaModulesValueDefaultProfileSuspension.js';
import {
    EncyclopediaModulesValueDefaultProfileSuspensionFromJSON,
    EncyclopediaModulesValueDefaultProfileSuspensionFromJSONTyped,
    EncyclopediaModulesValueDefaultProfileSuspensionToJSON,
    EncyclopediaModulesValueDefaultProfileSuspensionToJSONTyped,
} from './EncyclopediaModulesValueDefaultProfileSuspension.js';
import type { EncyclopediaModulesValueDefaultProfileTurret } from './EncyclopediaModulesValueDefaultProfileTurret.js';
import {
    EncyclopediaModulesValueDefaultProfileTurretFromJSON,
    EncyclopediaModulesValueDefaultProfileTurretFromJSONTyped,
    EncyclopediaModulesValueDefaultProfileTurretToJSON,
    EncyclopediaModulesValueDefaultProfileTurretToJSONTyped,
} from './EncyclopediaModulesValueDefaultProfileTurret.js';

/**
 * Basic technical characteristics of module.
 * @export
 * @interface EncyclopediaModulesValueDefaultProfile
 */
export interface EncyclopediaModulesValueDefaultProfile {
    /**
     * 
     * @type {EncyclopediaModulesValueDefaultProfileGun}
     * @memberof EncyclopediaModulesValueDefaultProfile
     */
    gun: EncyclopediaModulesValueDefaultProfileGun;
    /**
     * 
     * @type {EncyclopediaModulesValueDefaultProfileEngine}
     * @memberof EncyclopediaModulesValueDefaultProfile
     */
    engine: EncyclopediaModulesValueDefaultProfileEngine;
    /**
     * 
     * @type {EncyclopediaModulesValueDefaultProfileTurret}
     * @memberof EncyclopediaModulesValueDefaultProfile
     */
    turret: EncyclopediaModulesValueDefaultProfileTurret;
    /**
     * 
     * @type {EncyclopediaModulesValueDefaultProfileSuspension}
     * @memberof EncyclopediaModulesValueDefaultProfile
     */
    suspension: EncyclopediaModulesValueDefaultProfileSuspension;
    /**
     * 
     * @type {EncyclopediaModulesValueDefaultProfileRadio}
     * @memberof EncyclopediaModulesValueDefaultProfile
     */
    radio: EncyclopediaModulesValueDefaultProfileRadio;
}

/**
 * Check if a given object implements the EncyclopediaModulesValueDefaultProfile interface.
 */
export function instanceOfEncyclopediaModulesValueDefaultProfile(value: object): value is EncyclopediaModulesValueDefaultProfile {
    if (!('gun' in value) || value['gun'] === undefined) return false;
    if (!('engine' in value) || value['engine'] === undefined) return false;
    if (!('turret' in value) || value['turret'] === undefined) return false;
    if (!('suspension' in value) || value['suspension'] === undefined) return false;
    if (!('radio' in value) || value['radio'] === undefined) return false;
    return true;
}

export function EncyclopediaModulesValueDefaultProfileFromJSON(json: any): EncyclopediaModulesValueDefaultProfile {
    return EncyclopediaModulesValueDefaultProfileFromJSONTyped(json, false);
}

export function EncyclopediaModulesValueDefaultProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaModulesValueDefaultProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'gun': EncyclopediaModulesValueDefaultProfileGunFromJSON(json['gun']),
        'engine': EncyclopediaModulesValueDefaultProfileEngineFromJSON(json['engine']),
        'turret': EncyclopediaModulesValueDefaultProfileTurretFromJSON(json['turret']),
        'suspension': EncyclopediaModulesValueDefaultProfileSuspensionFromJSON(json['suspension']),
        'radio': EncyclopediaModulesValueDefaultProfileRadioFromJSON(json['radio']),
    };
}

export function EncyclopediaModulesValueDefaultProfileToJSON(json: any): EncyclopediaModulesValueDefaultProfile {
    return EncyclopediaModulesValueDefaultProfileToJSONTyped(json, false);
}

export function EncyclopediaModulesValueDefaultProfileToJSONTyped(value?: EncyclopediaModulesValueDefaultProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gun': EncyclopediaModulesValueDefaultProfileGunToJSON(value['gun']),
        'engine': EncyclopediaModulesValueDefaultProfileEngineToJSON(value['engine']),
        'turret': EncyclopediaModulesValueDefaultProfileTurretToJSON(value['turret']),
        'suspension': EncyclopediaModulesValueDefaultProfileSuspensionToJSON(value['suspension']),
        'radio': EncyclopediaModulesValueDefaultProfileRadioToJSON(value['radio']),
    };
}

