/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EncyclopediaVehiclesMeta } from './EncyclopediaVehiclesMeta.js';
import {
    EncyclopediaVehiclesMetaFromJSON,
    EncyclopediaVehiclesMetaFromJSONTyped,
    EncyclopediaVehiclesMetaToJSON,
    EncyclopediaVehiclesMetaToJSONTyped,
} from './EncyclopediaVehiclesMeta.js';
import type { EncyclopediaVehiclesDataValue } from './EncyclopediaVehiclesDataValue.js';
import {
    EncyclopediaVehiclesDataValueFromJSON,
    EncyclopediaVehiclesDataValueFromJSONTyped,
    EncyclopediaVehiclesDataValueToJSON,
    EncyclopediaVehiclesDataValueToJSONTyped,
} from './EncyclopediaVehiclesDataValue.js';

/**
 * 
 * @export
 * @interface EncyclopediaVehiclesOk
 */
export interface EncyclopediaVehiclesOk {
    /**
     * 
     * @type {string}
     * @memberof EncyclopediaVehiclesOk
     */
    status: EncyclopediaVehiclesOkStatusEnum;
    /**
     * 
     * @type {EncyclopediaVehiclesMeta}
     * @memberof EncyclopediaVehiclesOk
     */
    meta: EncyclopediaVehiclesMeta;
    /**
     * 
     * @type {{ [key: string]: EncyclopediaVehiclesDataValue | undefined; }}
     * @memberof EncyclopediaVehiclesOk
     */
    data: { [key: string]: EncyclopediaVehiclesDataValue | undefined; };
}

/**
* @export
* @enum {string}
*/
export enum EncyclopediaVehiclesOkStatusEnum {
    Ok = 'ok'
}


/**
 * Check if a given object implements the EncyclopediaVehiclesOk interface.
 */
export function instanceOfEncyclopediaVehiclesOk(value: object): value is EncyclopediaVehiclesOk {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function EncyclopediaVehiclesOkFromJSON(json: any): EncyclopediaVehiclesOk {
    return EncyclopediaVehiclesOkFromJSONTyped(json, false);
}

export function EncyclopediaVehiclesOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaVehiclesOk {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'meta': EncyclopediaVehiclesMetaFromJSON(json['meta']),
        'data': (mapValues(json['data'], EncyclopediaVehiclesDataValueFromJSON)),
    };
}

export function EncyclopediaVehiclesOkToJSON(json: any): EncyclopediaVehiclesOk {
    return EncyclopediaVehiclesOkToJSONTyped(json, false);
}

export function EncyclopediaVehiclesOkToJSONTyped(value?: EncyclopediaVehiclesOk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'meta': EncyclopediaVehiclesMetaToJSON(value['meta']),
        'data': (mapValues(value['data'], EncyclopediaVehiclesDataValueToJSON)),
    };
}

export const EncyclopediaVehiclesOkPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

