/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EncyclopediaPersonalmissionsValueOperationsValue } from './EncyclopediaPersonalmissionsValueOperationsValue.js';
import {
    EncyclopediaPersonalmissionsValueOperationsValueFromJSON,
    EncyclopediaPersonalmissionsValueOperationsValueFromJSONTyped,
    EncyclopediaPersonalmissionsValueOperationsValueToJSON,
    EncyclopediaPersonalmissionsValueOperationsValueToJSONTyped,
} from './EncyclopediaPersonalmissionsValueOperationsValue.js';

/**
 * 
 * @export
 * @interface EncyclopediaPersonalmissionsValue
 */
export interface EncyclopediaPersonalmissionsValue {
    /**
     * Campaign ID
     * @type {number}
     * @memberof EncyclopediaPersonalmissionsValue
     */
    campaignId: number;
    /**
     * Campaign name
     * @type {string}
     * @memberof EncyclopediaPersonalmissionsValue
     */
    name: string;
    /**
     * Campaign description
     * @type {string}
     * @memberof EncyclopediaPersonalmissionsValue
     */
    description: string;
    /**
     * 
     * @type {{ [key: string]: EncyclopediaPersonalmissionsValueOperationsValue; }}
     * @memberof EncyclopediaPersonalmissionsValue
     */
    operations: { [key: string]: EncyclopediaPersonalmissionsValueOperationsValue; };
}

/**
 * Check if a given object implements the EncyclopediaPersonalmissionsValue interface.
 */
export function instanceOfEncyclopediaPersonalmissionsValue(value: object): value is EncyclopediaPersonalmissionsValue {
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('operations' in value) || value['operations'] === undefined) return false;
    return true;
}

export function EncyclopediaPersonalmissionsValueFromJSON(json: any): EncyclopediaPersonalmissionsValue {
    return EncyclopediaPersonalmissionsValueFromJSONTyped(json, false);
}

export function EncyclopediaPersonalmissionsValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaPersonalmissionsValue {
    if (json == null) {
        return json;
    }
    return {
        
        'campaignId': json['campaign_id'],
        'name': json['name'],
        'description': json['description'],
        'operations': (mapValues(json['operations'], EncyclopediaPersonalmissionsValueOperationsValueFromJSON)),
    };
}

export function EncyclopediaPersonalmissionsValueToJSON(json: any): EncyclopediaPersonalmissionsValue {
    return EncyclopediaPersonalmissionsValueToJSONTyped(json, false);
}

export function EncyclopediaPersonalmissionsValueToJSONTyped(value?: EncyclopediaPersonalmissionsValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaign_id': value['campaignId'],
        'name': value['name'],
        'description': value['description'],
        'operations': (mapValues(value['operations'], EncyclopediaPersonalmissionsValueOperationsValueToJSON)),
    };
}

