/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AccountListErrorErrorOneOf3 } from './AccountListErrorErrorOneOf3.js';
import {
    instanceOfAccountListErrorErrorOneOf3,
    AccountListErrorErrorOneOf3FromJSON,
    AccountListErrorErrorOneOf3FromJSONTyped,
    AccountListErrorErrorOneOf3ToJSON,
} from './AccountListErrorErrorOneOf3.js';
import type { EncyclopediaVehicleprofileErrorErrorOneOf } from './EncyclopediaVehicleprofileErrorErrorOneOf.js';
import {
    instanceOfEncyclopediaVehicleprofileErrorErrorOneOf,
    EncyclopediaVehicleprofileErrorErrorOneOfFromJSON,
    EncyclopediaVehicleprofileErrorErrorOneOfFromJSONTyped,
    EncyclopediaVehicleprofileErrorErrorOneOfToJSON,
} from './EncyclopediaVehicleprofileErrorErrorOneOf.js';
import type { EncyclopediaVehicleprofileErrorErrorOneOf1 } from './EncyclopediaVehicleprofileErrorErrorOneOf1.js';
import {
    instanceOfEncyclopediaVehicleprofileErrorErrorOneOf1,
    EncyclopediaVehicleprofileErrorErrorOneOf1FromJSON,
    EncyclopediaVehicleprofileErrorErrorOneOf1FromJSONTyped,
    EncyclopediaVehicleprofileErrorErrorOneOf1ToJSON,
} from './EncyclopediaVehicleprofileErrorErrorOneOf1.js';

/**
 * @type EncyclopediaVehicleprofileErrorError
 * 
 * @export
 */
export type EncyclopediaVehicleprofileErrorError = AccountListErrorErrorOneOf3 | EncyclopediaVehicleprofileErrorErrorOneOf | EncyclopediaVehicleprofileErrorErrorOneOf1;

export function EncyclopediaVehicleprofileErrorErrorFromJSON(json: any): EncyclopediaVehicleprofileErrorError {
    return EncyclopediaVehicleprofileErrorErrorFromJSONTyped(json, false);
}

export function EncyclopediaVehicleprofileErrorErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaVehicleprofileErrorError {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAccountListErrorErrorOneOf3(json)) {
        return AccountListErrorErrorOneOf3FromJSONTyped(json, true);
    }
    if (instanceOfEncyclopediaVehicleprofileErrorErrorOneOf(json)) {
        return EncyclopediaVehicleprofileErrorErrorOneOfFromJSONTyped(json, true);
    }
    if (instanceOfEncyclopediaVehicleprofileErrorErrorOneOf1(json)) {
        return EncyclopediaVehicleprofileErrorErrorOneOf1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function EncyclopediaVehicleprofileErrorErrorToJSON(json: any): any {
    return EncyclopediaVehicleprofileErrorErrorToJSONTyped(json, false);
}

export function EncyclopediaVehicleprofileErrorErrorToJSONTyped(value?: EncyclopediaVehicleprofileErrorError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAccountListErrorErrorOneOf3(value)) {
        return AccountListErrorErrorOneOf3ToJSON(value as AccountListErrorErrorOneOf3);
    }
    if (instanceOfEncyclopediaVehicleprofileErrorErrorOneOf(value)) {
        return EncyclopediaVehicleprofileErrorErrorOneOfToJSON(value as EncyclopediaVehicleprofileErrorErrorOneOf);
    }
    if (instanceOfEncyclopediaVehicleprofileErrorErrorOneOf1(value)) {
        return EncyclopediaVehicleprofileErrorErrorOneOf1ToJSON(value as EncyclopediaVehicleprofileErrorErrorOneOf1);
    }

    return {};
}

