/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Specified configuration does not exist
 * @export
 * @interface EncyclopediaVehicleprofileErrorErrorOneOf1
 */
export interface EncyclopediaVehicleprofileErrorErrorOneOf1 {
    /**
     * 
     * @type {number}
     * @memberof EncyclopediaVehicleprofileErrorErrorOneOf1
     */
    code: EncyclopediaVehicleprofileErrorErrorOneOf1CodeEnum;
    /**
     * 
     * @type {string}
     * @memberof EncyclopediaVehicleprofileErrorErrorOneOf1
     */
    message: EncyclopediaVehicleprofileErrorErrorOneOf1MessageEnum;
    /**
     * 
     * @type {string}
     * @memberof EncyclopediaVehicleprofileErrorErrorOneOf1
     */
    field: string | null;
    /**
     * 
     * @type {string}
     * @memberof EncyclopediaVehicleprofileErrorErrorOneOf1
     */
    value: string | null;
}


/**
 * @export
 */
export const EncyclopediaVehicleprofileErrorErrorOneOf1CodeEnum = {
    NUMBER_404: 404
} as const;
export type EncyclopediaVehicleprofileErrorErrorOneOf1CodeEnum = typeof EncyclopediaVehicleprofileErrorErrorOneOf1CodeEnum[keyof typeof EncyclopediaVehicleprofileErrorErrorOneOf1CodeEnum];

/**
 * @export
 */
export const EncyclopediaVehicleprofileErrorErrorOneOf1MessageEnum = {
    ProfileNotFound: 'PROFILE_NOT_FOUND'
} as const;
export type EncyclopediaVehicleprofileErrorErrorOneOf1MessageEnum = typeof EncyclopediaVehicleprofileErrorErrorOneOf1MessageEnum[keyof typeof EncyclopediaVehicleprofileErrorErrorOneOf1MessageEnum];


/**
 * Check if a given object implements the EncyclopediaVehicleprofileErrorErrorOneOf1 interface.
 */
export function instanceOfEncyclopediaVehicleprofileErrorErrorOneOf1(value: object): value is EncyclopediaVehicleprofileErrorErrorOneOf1 {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function EncyclopediaVehicleprofileErrorErrorOneOf1FromJSON(json: any): EncyclopediaVehicleprofileErrorErrorOneOf1 {
    return EncyclopediaVehicleprofileErrorErrorOneOf1FromJSONTyped(json, false);
}

export function EncyclopediaVehicleprofileErrorErrorOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaVehicleprofileErrorErrorOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'field': json['field'],
        'value': json['value'],
    };
}

export function EncyclopediaVehicleprofileErrorErrorOneOf1ToJSON(json: any): EncyclopediaVehicleprofileErrorErrorOneOf1 {
    return EncyclopediaVehicleprofileErrorErrorOneOf1ToJSONTyped(json, false);
}

export function EncyclopediaVehicleprofileErrorErrorOneOf1ToJSONTyped(value?: EncyclopediaVehicleprofileErrorErrorOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'field': value['field'],
        'value': value['value'],
    };
}

