/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface EncyclopediaVehiclesMeta
 */
export interface EncyclopediaVehiclesMeta {
    /**
     * 
     * @type {number}
     * @memberof EncyclopediaVehiclesMeta
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof EncyclopediaVehiclesMeta
     */
    page_total: number | null;
    /**
     * 
     * @type {number}
     * @memberof EncyclopediaVehiclesMeta
     */
    total: number | null;
    /**
     * 
     * @type {number}
     * @memberof EncyclopediaVehiclesMeta
     */
    limit: number | null;
    /**
     * 
     * @type {number}
     * @memberof EncyclopediaVehiclesMeta
     */
    page: number | null;
}

/**
 * Check if a given object implements the EncyclopediaVehiclesMeta interface.
 */
export function instanceOfEncyclopediaVehiclesMeta(value: object): value is EncyclopediaVehiclesMeta {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('page_total' in value) || value['page_total'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    return true;
}

export function EncyclopediaVehiclesMetaFromJSON(json: any): EncyclopediaVehiclesMeta {
    return EncyclopediaVehiclesMetaFromJSONTyped(json, false);
}

export function EncyclopediaVehiclesMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaVehiclesMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'page_total': json['page_total'],
        'total': json['total'],
        'limit': json['limit'],
        'page': json['page'],
    };
}

export function EncyclopediaVehiclesMetaToJSON(json: any): EncyclopediaVehiclesMeta {
    return EncyclopediaVehiclesMetaToJSONTyped(json, false);
}

export function EncyclopediaVehiclesMetaToJSONTyped(value?: EncyclopediaVehiclesMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'page_total': value['page_total'],
        'total': value['total'],
        'limit': value['limit'],
        'page': value['page'],
    };
}

export const EncyclopediaVehiclesMetaPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

