/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AccountListErrorErrorOneOf3 } from './AccountListErrorErrorOneOf3.js';
import {
    AccountListErrorErrorOneOf3FromJSON,
    AccountListErrorErrorOneOf3FromJSONTyped,
    AccountListErrorErrorOneOf3ToJSON,
    AccountListErrorErrorOneOf3ToJSONTyped,
} from './AccountListErrorErrorOneOf3.js';

/**
 * 
 * @export
 * @interface EncyclopediaVehicleprofilesError
 */
export interface EncyclopediaVehicleprofilesError {
    /**
     * 
     * @type {string}
     * @memberof EncyclopediaVehicleprofilesError
     */
    status: EncyclopediaVehicleprofilesErrorStatusEnum;
    /**
     * 
     * @type {AccountListErrorErrorOneOf3}
     * @memberof EncyclopediaVehicleprofilesError
     */
    error: AccountListErrorErrorOneOf3;
}


/**
 * @export
 */
export const EncyclopediaVehicleprofilesErrorStatusEnum = {
    Error: 'error'
} as const;
export type EncyclopediaVehicleprofilesErrorStatusEnum = typeof EncyclopediaVehicleprofilesErrorStatusEnum[keyof typeof EncyclopediaVehicleprofilesErrorStatusEnum];


/**
 * Check if a given object implements the EncyclopediaVehicleprofilesError interface.
 */
export function instanceOfEncyclopediaVehicleprofilesError(value: object): value is EncyclopediaVehicleprofilesError {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function EncyclopediaVehicleprofilesErrorFromJSON(json: any): EncyclopediaVehicleprofilesError {
    return EncyclopediaVehicleprofilesErrorFromJSONTyped(json, false);
}

export function EncyclopediaVehicleprofilesErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaVehicleprofilesError {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'error': AccountListErrorErrorOneOf3FromJSON(json['error']),
    };
}

export function EncyclopediaVehicleprofilesErrorToJSON(json: any): EncyclopediaVehicleprofilesError {
    return EncyclopediaVehicleprofilesErrorToJSONTyped(json, false);
}

export function EncyclopediaVehicleprofilesErrorToJSONTyped(value?: EncyclopediaVehicleprofilesError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'error': AccountListErrorErrorOneOf3ToJSON(value['error']),
    };
}

