/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Gun characteristics
 * @export
 * @interface EncyclopediaVehiclesValueDefaultProfileGun
 */
export interface EncyclopediaVehiclesValueDefaultProfileGun {
    /**
     * Tier
     * @type {number}
     * @memberof EncyclopediaVehiclesValueDefaultProfileGun
     */
    tier: number;
    /**
     * Module name
     * @type {string}
     * @memberof EncyclopediaVehiclesValueDefaultProfileGun
     */
    name: string;
    /**
     * Weight (kg)
     * @type {number}
     * @memberof EncyclopediaVehiclesValueDefaultProfileGun
     */
    weight: number;
    /**
     * Module tag
     * @type {string}
     * @memberof EncyclopediaVehiclesValueDefaultProfileGun
     */
    tag: string;
    /**
     * Rate of fire (rounds/min)
     * @type {number}
     * @memberof EncyclopediaVehiclesValueDefaultProfileGun
     */
    fireRate: number;
    /**
     * Dispersion at 100 m (m)
     * @type {number}
     * @memberof EncyclopediaVehiclesValueDefaultProfileGun
     */
    dispersion: number;
    /**
     * Aiming time (s)
     * @type {number}
     * @memberof EncyclopediaVehiclesValueDefaultProfileGun
     */
    aimTime: number;
    /**
     * Reload time (s)
     * @type {number}
     * @memberof EncyclopediaVehiclesValueDefaultProfileGun
     */
    reloadTime: number;
    /**
     * Caliber (mm)
     * @type {number}
     * @memberof EncyclopediaVehiclesValueDefaultProfileGun
     */
    caliber: number;
    /**
     * Elevation angle (deg)
     * @type {number}
     * @memberof EncyclopediaVehiclesValueDefaultProfileGun
     */
    moveUpArc: number;
    /**
     * Depression angle (deg)
     * @type {number}
     * @memberof EncyclopediaVehiclesValueDefaultProfileGun
     */
    moveDownArc: number;
    /**
     * Traverse speed (deg/s)
     * @type {number}
     * @memberof EncyclopediaVehiclesValueDefaultProfileGun
     */
    traverseSpeed: number;
}

/**
 * Check if a given object implements the EncyclopediaVehiclesValueDefaultProfileGun interface.
 */
export function instanceOfEncyclopediaVehiclesValueDefaultProfileGun(value: object): value is EncyclopediaVehiclesValueDefaultProfileGun {
    if (!('tier' in value) || value['tier'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('fireRate' in value) || value['fireRate'] === undefined) return false;
    if (!('dispersion' in value) || value['dispersion'] === undefined) return false;
    if (!('aimTime' in value) || value['aimTime'] === undefined) return false;
    if (!('reloadTime' in value) || value['reloadTime'] === undefined) return false;
    if (!('caliber' in value) || value['caliber'] === undefined) return false;
    if (!('moveUpArc' in value) || value['moveUpArc'] === undefined) return false;
    if (!('moveDownArc' in value) || value['moveDownArc'] === undefined) return false;
    if (!('traverseSpeed' in value) || value['traverseSpeed'] === undefined) return false;
    return true;
}

export function EncyclopediaVehiclesValueDefaultProfileGunFromJSON(json: any): EncyclopediaVehiclesValueDefaultProfileGun {
    return EncyclopediaVehiclesValueDefaultProfileGunFromJSONTyped(json, false);
}

export function EncyclopediaVehiclesValueDefaultProfileGunFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaVehiclesValueDefaultProfileGun {
    if (json == null) {
        return json;
    }
    return {
        
        'tier': json['tier'],
        'name': json['name'],
        'weight': json['weight'],
        'tag': json['tag'],
        'fireRate': json['fire_rate'],
        'dispersion': json['dispersion'],
        'aimTime': json['aim_time'],
        'reloadTime': json['reload_time'],
        'caliber': json['caliber'],
        'moveUpArc': json['move_up_arc'],
        'moveDownArc': json['move_down_arc'],
        'traverseSpeed': json['traverse_speed'],
    };
}

export function EncyclopediaVehiclesValueDefaultProfileGunToJSON(json: any): EncyclopediaVehiclesValueDefaultProfileGun {
    return EncyclopediaVehiclesValueDefaultProfileGunToJSONTyped(json, false);
}

export function EncyclopediaVehiclesValueDefaultProfileGunToJSONTyped(value?: EncyclopediaVehiclesValueDefaultProfileGun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tier': value['tier'],
        'name': value['name'],
        'weight': value['weight'],
        'tag': value['tag'],
        'fire_rate': value['fireRate'],
        'dispersion': value['dispersion'],
        'aim_time': value['aimTime'],
        'reload_time': value['reloadTime'],
        'caliber': value['caliber'],
        'move_up_arc': value['moveUpArc'],
        'move_down_arc': value['moveDownArc'],
        'traverse_speed': value['traverseSpeed'],
    };
}

