/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface EncyclopediaVehiclesValueCrewItem
 */
export interface EncyclopediaVehiclesValueCrewItem {
    /**
     * Crew member ID
     * @type {string}
     * @memberof EncyclopediaVehiclesValueCrewItem
     */
    memberId: string;
    /**
     * List of crew member roles
     * @type {{ [key: string]: string; }}
     * @memberof EncyclopediaVehiclesValueCrewItem
     */
    roles: { [key: string]: string; };
}

/**
 * Check if a given object implements the EncyclopediaVehiclesValueCrewItem interface.
 */
export function instanceOfEncyclopediaVehiclesValueCrewItem(value: object): value is EncyclopediaVehiclesValueCrewItem {
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    return true;
}

export function EncyclopediaVehiclesValueCrewItemFromJSON(json: any): EncyclopediaVehiclesValueCrewItem {
    return EncyclopediaVehiclesValueCrewItemFromJSONTyped(json, false);
}

export function EncyclopediaVehiclesValueCrewItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaVehiclesValueCrewItem {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['member_id'],
        'roles': json['roles'],
    };
}

export function EncyclopediaVehiclesValueCrewItemToJSON(json: any): EncyclopediaVehiclesValueCrewItem {
    return EncyclopediaVehiclesValueCrewItemToJSONTyped(json, false);
}

export function EncyclopediaVehiclesValueCrewItemToJSONTyped(value?: EncyclopediaVehiclesValueCrewItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member_id': value['memberId'],
        'roles': value['roles'],
    };
}

