/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EncyclopediaVehicleprofilesError } from './EncyclopediaVehicleprofilesError.js';
import {
    instanceOfEncyclopediaVehicleprofilesError,
    EncyclopediaVehicleprofilesErrorFromJSON,
    EncyclopediaVehicleprofilesErrorFromJSONTyped,
    EncyclopediaVehicleprofilesErrorToJSON,
} from './EncyclopediaVehicleprofilesError.js';
import type { EncyclopediaVehicleprofilesOk } from './EncyclopediaVehicleprofilesOk.js';
import {
    instanceOfEncyclopediaVehicleprofilesOk,
    EncyclopediaVehicleprofilesOkFromJSON,
    EncyclopediaVehicleprofilesOkFromJSONTyped,
    EncyclopediaVehicleprofilesOkToJSON,
} from './EncyclopediaVehicleprofilesOk.js';

/**
 * @type EncyclopediaVehicleprofilesResponse
 * 
 * @export
 */
export type EncyclopediaVehicleprofilesResponse = EncyclopediaVehicleprofilesError | EncyclopediaVehicleprofilesOk;

export function EncyclopediaVehicleprofilesResponseFromJSON(json: any): EncyclopediaVehicleprofilesResponse {
    return EncyclopediaVehicleprofilesResponseFromJSONTyped(json, false);
}

export function EncyclopediaVehicleprofilesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaVehicleprofilesResponse {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEncyclopediaVehicleprofilesError(json)) {
        return EncyclopediaVehicleprofilesErrorFromJSONTyped(json, true);
    }
    if (instanceOfEncyclopediaVehicleprofilesOk(json)) {
        return EncyclopediaVehicleprofilesOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function EncyclopediaVehicleprofilesResponseToJSON(json: any): any {
    return EncyclopediaVehicleprofilesResponseToJSONTyped(json, false);
}

export function EncyclopediaVehicleprofilesResponseToJSONTyped(value?: EncyclopediaVehicleprofilesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEncyclopediaVehicleprofilesError(value)) {
        return EncyclopediaVehicleprofilesErrorToJSON(value as EncyclopediaVehicleprofilesError);
    }
    if (instanceOfEncyclopediaVehicleprofilesOk(value)) {
        return EncyclopediaVehicleprofilesOkToJSON(value as EncyclopediaVehicleprofilesOk);
    }

    return {};
}

