/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface EncyclopediaArenasMeta
 */
export interface EncyclopediaArenasMeta {
    /**
     * 
     * @type {number}
     * @memberof EncyclopediaArenasMeta
     */
    count: number;
}

/**
 * Check if a given object implements the EncyclopediaArenasMeta interface.
 */
export function instanceOfEncyclopediaArenasMeta(value: object): value is EncyclopediaArenasMeta {
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function EncyclopediaArenasMetaFromJSON(json: any): EncyclopediaArenasMeta {
    return EncyclopediaArenasMetaFromJSONTyped(json, false);
}

export function EncyclopediaArenasMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaArenasMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
    };
}

export function EncyclopediaArenasMetaToJSON(json: any): EncyclopediaArenasMeta {
    return EncyclopediaArenasMetaToJSONTyped(json, false);
}

export function EncyclopediaArenasMetaToJSONTyped(value?: EncyclopediaArenasMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
    };
}

