/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Reward for operation
 * @export
 * @interface EncyclopediaPersonalmissionsDataValueOperationsValueReward
 */
export interface EncyclopediaPersonalmissionsDataValueOperationsValueReward {
    /**
     * Slots
     * @type {number}
     * @memberof EncyclopediaPersonalmissionsDataValueOperationsValueReward
     */
    slots: number | null;
    /**
     * Vehicle IDs
     * @type {Array<number>}
     * @memberof EncyclopediaPersonalmissionsDataValueOperationsValueReward
     */
    tanks: Array<number>;
}

/**
 * Check if a given object implements the EncyclopediaPersonalmissionsDataValueOperationsValueReward interface.
 */
export function instanceOfEncyclopediaPersonalmissionsDataValueOperationsValueReward(value: object): value is EncyclopediaPersonalmissionsDataValueOperationsValueReward {
    if (!('slots' in value) || value['slots'] === undefined) return false;
    if (!('tanks' in value) || value['tanks'] === undefined) return false;
    return true;
}

export function EncyclopediaPersonalmissionsDataValueOperationsValueRewardFromJSON(json: any): EncyclopediaPersonalmissionsDataValueOperationsValueReward {
    return EncyclopediaPersonalmissionsDataValueOperationsValueRewardFromJSONTyped(json, false);
}

export function EncyclopediaPersonalmissionsDataValueOperationsValueRewardFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaPersonalmissionsDataValueOperationsValueReward {
    if (json == null) {
        return json;
    }
    return {
        
        'slots': json['slots'],
        'tanks': json['tanks'],
    };
}

export function EncyclopediaPersonalmissionsDataValueOperationsValueRewardToJSON(json: any): EncyclopediaPersonalmissionsDataValueOperationsValueReward {
    return EncyclopediaPersonalmissionsDataValueOperationsValueRewardToJSONTyped(json, false);
}

export function EncyclopediaPersonalmissionsDataValueOperationsValueRewardToJSONTyped(value?: EncyclopediaPersonalmissionsDataValueOperationsValueReward | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slots': value['slots'],
        'tanks': value['tanks'],
    };
}

export const EncyclopediaPersonalmissionsDataValueOperationsValueRewardPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

