/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Hull armor
 * @export
 * @interface EncyclopediaVehiclesDataValueDefaultProfileArmorHull
 */
export interface EncyclopediaVehiclesDataValueDefaultProfileArmorHull {
    /**
     * Front (mm)
     * @type {number}
     * @memberof EncyclopediaVehiclesDataValueDefaultProfileArmorHull
     */
    front: number;
    /**
     * Sides (mm)
     * @type {number}
     * @memberof EncyclopediaVehiclesDataValueDefaultProfileArmorHull
     */
    sides: number;
    /**
     * Rear (mm)
     * @type {number}
     * @memberof EncyclopediaVehiclesDataValueDefaultProfileArmorHull
     */
    rear: number;
}

/**
 * Check if a given object implements the EncyclopediaVehiclesDataValueDefaultProfileArmorHull interface.
 */
export function instanceOfEncyclopediaVehiclesDataValueDefaultProfileArmorHull(value: object): value is EncyclopediaVehiclesDataValueDefaultProfileArmorHull {
    if (!('front' in value) || value['front'] === undefined) return false;
    if (!('sides' in value) || value['sides'] === undefined) return false;
    if (!('rear' in value) || value['rear'] === undefined) return false;
    return true;
}

export function EncyclopediaVehiclesDataValueDefaultProfileArmorHullFromJSON(json: any): EncyclopediaVehiclesDataValueDefaultProfileArmorHull {
    return EncyclopediaVehiclesDataValueDefaultProfileArmorHullFromJSONTyped(json, false);
}

export function EncyclopediaVehiclesDataValueDefaultProfileArmorHullFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncyclopediaVehiclesDataValueDefaultProfileArmorHull {
    if (json == null) {
        return json;
    }
    return {
        
        'front': json['front'],
        'sides': json['sides'],
        'rear': json['rear'],
    };
}

export function EncyclopediaVehiclesDataValueDefaultProfileArmorHullToJSON(json: any): EncyclopediaVehiclesDataValueDefaultProfileArmorHull {
    return EncyclopediaVehiclesDataValueDefaultProfileArmorHullToJSONTyped(json, false);
}

export function EncyclopediaVehiclesDataValueDefaultProfileArmorHullToJSONTyped(value?: EncyclopediaVehiclesDataValueDefaultProfileArmorHull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'front': value['front'],
        'sides': value['sides'],
        'rear': value['rear'],
    };
}

export const EncyclopediaVehiclesDataValueDefaultProfileArmorHullPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

