/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AccountListError } from './AccountListError.js';
import {
    instanceOfAccountListError,
    AccountListErrorFromJSON,
    AccountListErrorFromJSONTyped,
    AccountListErrorToJSON,
} from './AccountListError.js';
import type { AccountListOk } from './AccountListOk.js';
import {
    instanceOfAccountListOk,
    AccountListOkFromJSON,
    AccountListOkFromJSONTyped,
    AccountListOkToJSON,
} from './AccountListOk.js';

/**
 * @type GetAccountList200Response
 * 
 * @export
 */
export type GetAccountList200Response = AccountListError | AccountListOk;

export function GetAccountList200ResponseFromJSON(json: any): GetAccountList200Response {
    return GetAccountList200ResponseFromJSONTyped(json, false);
}

export function GetAccountList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountList200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAccountListError(json)) {
        return AccountListErrorFromJSONTyped(json, true);
    }
    if (instanceOfAccountListOk(json)) {
        return AccountListOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetAccountList200ResponseToJSON(json: any): any {
    return GetAccountList200ResponseToJSONTyped(json, false);
}

export function GetAccountList200ResponseToJSONTyped(value?: GetAccountList200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAccountListError(value)) {
        return AccountListErrorToJSON(value as AccountListError);
    }
    if (instanceOfAccountListOk(value)) {
        return AccountListOkToJSON(value as AccountListOk);
    }

    return {};
}

