/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ClanratingsTypesError } from './ClanratingsTypesError.js';
import {
    instanceOfClanratingsTypesError,
    ClanratingsTypesErrorFromJSON,
    ClanratingsTypesErrorFromJSONTyped,
    ClanratingsTypesErrorToJSON,
} from './ClanratingsTypesError.js';
import type { ClanratingsTypesOk } from './ClanratingsTypesOk.js';
import {
    instanceOfClanratingsTypesOk,
    ClanratingsTypesOkFromJSON,
    ClanratingsTypesOkFromJSONTyped,
    ClanratingsTypesOkToJSON,
} from './ClanratingsTypesOk.js';

/**
 * @type GetClanratingsTypes200Response
 * 
 * @export
 */
export type GetClanratingsTypes200Response = ClanratingsTypesError | ClanratingsTypesOk;

export function GetClanratingsTypes200ResponseFromJSON(json: any): GetClanratingsTypes200Response {
    return GetClanratingsTypes200ResponseFromJSONTyped(json, false);
}

export function GetClanratingsTypes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClanratingsTypes200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfClanratingsTypesError(json)) {
        return ClanratingsTypesErrorFromJSONTyped(json, true);
    }
    if (instanceOfClanratingsTypesOk(json)) {
        return ClanratingsTypesOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetClanratingsTypes200ResponseToJSON(json: any): any {
    return GetClanratingsTypes200ResponseToJSONTyped(json, false);
}

export function GetClanratingsTypes200ResponseToJSONTyped(value?: GetClanratingsTypes200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfClanratingsTypesError(value)) {
        return ClanratingsTypesErrorToJSON(value as ClanratingsTypesError);
    }
    if (instanceOfClanratingsTypesOk(value)) {
        return ClanratingsTypesOkToJSON(value as ClanratingsTypesOk);
    }

    return {};
}

