/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ClanratingsTopError } from './ClanratingsTopError.js';
import {
    instanceOfClanratingsTopError,
    ClanratingsTopErrorFromJSON,
    ClanratingsTopErrorFromJSONTyped,
    ClanratingsTopErrorToJSON,
} from './ClanratingsTopError.js';
import type { ClanratingsTopOk } from './ClanratingsTopOk.js';
import {
    instanceOfClanratingsTopOk,
    ClanratingsTopOkFromJSON,
    ClanratingsTopOkFromJSONTyped,
    ClanratingsTopOkToJSON,
} from './ClanratingsTopOk.js';

/**
 * @type GetClanratingsTop200Response
 * 
 * @export
 */
export type GetClanratingsTop200Response = ClanratingsTopError | ClanratingsTopOk;

export function GetClanratingsTop200ResponseFromJSON(json: any): GetClanratingsTop200Response {
    return GetClanratingsTop200ResponseFromJSONTyped(json, false);
}

export function GetClanratingsTop200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClanratingsTop200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfClanratingsTopError(json)) {
        return ClanratingsTopErrorFromJSONTyped(json, true);
    }
    if (instanceOfClanratingsTopOk(json)) {
        return ClanratingsTopOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetClanratingsTop200ResponseToJSON(json: any): any {
    return GetClanratingsTop200ResponseToJSONTyped(json, false);
}

export function GetClanratingsTop200ResponseToJSONTyped(value?: GetClanratingsTop200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfClanratingsTopError(value)) {
        return ClanratingsTopErrorToJSON(value as ClanratingsTopError);
    }
    if (instanceOfClanratingsTopOk(value)) {
        return ClanratingsTopOkToJSON(value as ClanratingsTopOk);
    }

    return {};
}

