/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EncyclopediaPersonalmissionsError } from './EncyclopediaPersonalmissionsError.js';
import {
    instanceOfEncyclopediaPersonalmissionsError,
    EncyclopediaPersonalmissionsErrorFromJSON,
    EncyclopediaPersonalmissionsErrorFromJSONTyped,
    EncyclopediaPersonalmissionsErrorToJSON,
} from './EncyclopediaPersonalmissionsError.js';
import type { EncyclopediaPersonalmissionsOk } from './EncyclopediaPersonalmissionsOk.js';
import {
    instanceOfEncyclopediaPersonalmissionsOk,
    EncyclopediaPersonalmissionsOkFromJSON,
    EncyclopediaPersonalmissionsOkFromJSONTyped,
    EncyclopediaPersonalmissionsOkToJSON,
} from './EncyclopediaPersonalmissionsOk.js';

/**
 * @type GetEncyclopediaPersonalmissions200Response
 * 
 * @export
 */
export type GetEncyclopediaPersonalmissions200Response = EncyclopediaPersonalmissionsError | EncyclopediaPersonalmissionsOk;

export function GetEncyclopediaPersonalmissions200ResponseFromJSON(json: any): GetEncyclopediaPersonalmissions200Response {
    return GetEncyclopediaPersonalmissions200ResponseFromJSONTyped(json, false);
}

export function GetEncyclopediaPersonalmissions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEncyclopediaPersonalmissions200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEncyclopediaPersonalmissionsError(json)) {
        return EncyclopediaPersonalmissionsErrorFromJSONTyped(json, true);
    }
    if (instanceOfEncyclopediaPersonalmissionsOk(json)) {
        return EncyclopediaPersonalmissionsOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetEncyclopediaPersonalmissions200ResponseToJSON(json: any): any {
    return GetEncyclopediaPersonalmissions200ResponseToJSONTyped(json, false);
}

export function GetEncyclopediaPersonalmissions200ResponseToJSONTyped(value?: GetEncyclopediaPersonalmissions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEncyclopediaPersonalmissionsError(value)) {
        return EncyclopediaPersonalmissionsErrorToJSON(value as EncyclopediaPersonalmissionsError);
    }
    if (instanceOfEncyclopediaPersonalmissionsOk(value)) {
        return EncyclopediaPersonalmissionsOkToJSON(value as EncyclopediaPersonalmissionsOk);
    }

    return {};
}

