/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EncyclopediaVehiclesError } from './EncyclopediaVehiclesError.js';
import {
    instanceOfEncyclopediaVehiclesError,
    EncyclopediaVehiclesErrorFromJSON,
    EncyclopediaVehiclesErrorFromJSONTyped,
    EncyclopediaVehiclesErrorToJSON,
} from './EncyclopediaVehiclesError.js';
import type { EncyclopediaVehiclesOk } from './EncyclopediaVehiclesOk.js';
import {
    instanceOfEncyclopediaVehiclesOk,
    EncyclopediaVehiclesOkFromJSON,
    EncyclopediaVehiclesOkFromJSONTyped,
    EncyclopediaVehiclesOkToJSON,
} from './EncyclopediaVehiclesOk.js';

/**
 * @type GetEncyclopediaVehicles200Response
 * 
 * @export
 */
export type GetEncyclopediaVehicles200Response = EncyclopediaVehiclesError | EncyclopediaVehiclesOk;

export function GetEncyclopediaVehicles200ResponseFromJSON(json: any): GetEncyclopediaVehicles200Response {
    return GetEncyclopediaVehicles200ResponseFromJSONTyped(json, false);
}

export function GetEncyclopediaVehicles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEncyclopediaVehicles200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEncyclopediaVehiclesError(json)) {
        return EncyclopediaVehiclesErrorFromJSONTyped(json, true);
    }
    if (instanceOfEncyclopediaVehiclesOk(json)) {
        return EncyclopediaVehiclesOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetEncyclopediaVehicles200ResponseToJSON(json: any): any {
    return GetEncyclopediaVehicles200ResponseToJSONTyped(json, false);
}

export function GetEncyclopediaVehicles200ResponseToJSONTyped(value?: GetEncyclopediaVehicles200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEncyclopediaVehiclesError(value)) {
        return EncyclopediaVehiclesErrorToJSON(value as EncyclopediaVehiclesError);
    }
    if (instanceOfEncyclopediaVehiclesOk(value)) {
        return EncyclopediaVehiclesOkToJSON(value as EncyclopediaVehiclesOk);
    }

    return {};
}

