/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EncyclopediaBoostersError } from './EncyclopediaBoostersError.js';
import {
    instanceOfEncyclopediaBoostersError,
    EncyclopediaBoostersErrorFromJSON,
    EncyclopediaBoostersErrorFromJSONTyped,
    EncyclopediaBoostersErrorToJSON,
} from './EncyclopediaBoostersError.js';
import type { EncyclopediaBoostersOk } from './EncyclopediaBoostersOk.js';
import {
    instanceOfEncyclopediaBoostersOk,
    EncyclopediaBoostersOkFromJSON,
    EncyclopediaBoostersOkFromJSONTyped,
    EncyclopediaBoostersOkToJSON,
} from './EncyclopediaBoostersOk.js';

/**
 * @type GetEncyclopediaBoosters200Response
 * 
 * @export
 */
export type GetEncyclopediaBoosters200Response = EncyclopediaBoostersError | EncyclopediaBoostersOk;

export function GetEncyclopediaBoosters200ResponseFromJSON(json: any): GetEncyclopediaBoosters200Response {
    return GetEncyclopediaBoosters200ResponseFromJSONTyped(json, false);
}

export function GetEncyclopediaBoosters200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEncyclopediaBoosters200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEncyclopediaBoostersError(json)) {
        return EncyclopediaBoostersErrorFromJSONTyped(json, true);
    }
    if (instanceOfEncyclopediaBoostersOk(json)) {
        return EncyclopediaBoostersOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetEncyclopediaBoosters200ResponseToJSON(json: any): any {
    return GetEncyclopediaBoosters200ResponseToJSONTyped(json, false);
}

export function GetEncyclopediaBoosters200ResponseToJSONTyped(value?: GetEncyclopediaBoosters200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEncyclopediaBoostersError(value)) {
        return EncyclopediaBoostersErrorToJSON(value as EncyclopediaBoostersError);
    }
    if (instanceOfEncyclopediaBoostersOk(value)) {
        return EncyclopediaBoostersOkToJSON(value as EncyclopediaBoostersOk);
    }

    return {};
}

