/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EncyclopediaModulesError } from './EncyclopediaModulesError.js';
import {
    instanceOfEncyclopediaModulesError,
    EncyclopediaModulesErrorFromJSON,
    EncyclopediaModulesErrorFromJSONTyped,
    EncyclopediaModulesErrorToJSON,
} from './EncyclopediaModulesError.js';
import type { EncyclopediaModulesOk } from './EncyclopediaModulesOk.js';
import {
    instanceOfEncyclopediaModulesOk,
    EncyclopediaModulesOkFromJSON,
    EncyclopediaModulesOkFromJSONTyped,
    EncyclopediaModulesOkToJSON,
} from './EncyclopediaModulesOk.js';

/**
 * @type GetEncyclopediaModules200Response
 * 
 * @export
 */
export type GetEncyclopediaModules200Response = EncyclopediaModulesError | EncyclopediaModulesOk;

export function GetEncyclopediaModules200ResponseFromJSON(json: any): GetEncyclopediaModules200Response {
    return GetEncyclopediaModules200ResponseFromJSONTyped(json, false);
}

export function GetEncyclopediaModules200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEncyclopediaModules200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEncyclopediaModulesError(json)) {
        return EncyclopediaModulesErrorFromJSONTyped(json, true);
    }
    if (instanceOfEncyclopediaModulesOk(json)) {
        return EncyclopediaModulesOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetEncyclopediaModules200ResponseToJSON(json: any): any {
    return GetEncyclopediaModules200ResponseToJSONTyped(json, false);
}

export function GetEncyclopediaModules200ResponseToJSONTyped(value?: GetEncyclopediaModules200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEncyclopediaModulesError(value)) {
        return EncyclopediaModulesErrorToJSON(value as EncyclopediaModulesError);
    }
    if (instanceOfEncyclopediaModulesOk(value)) {
        return EncyclopediaModulesOkToJSON(value as EncyclopediaModulesOk);
    }

    return {};
}

