/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EncyclopediaInfoError } from './EncyclopediaInfoError.js';
import {
    instanceOfEncyclopediaInfoError,
    EncyclopediaInfoErrorFromJSON,
    EncyclopediaInfoErrorFromJSONTyped,
    EncyclopediaInfoErrorToJSON,
} from './EncyclopediaInfoError.js';
import type { EncyclopediaInfoOk } from './EncyclopediaInfoOk.js';
import {
    instanceOfEncyclopediaInfoOk,
    EncyclopediaInfoOkFromJSON,
    EncyclopediaInfoOkFromJSONTyped,
    EncyclopediaInfoOkToJSON,
} from './EncyclopediaInfoOk.js';

/**
 * @type GetEncyclopediaInfo200Response
 * 
 * @export
 */
export type GetEncyclopediaInfo200Response = EncyclopediaInfoError | EncyclopediaInfoOk;

export function GetEncyclopediaInfo200ResponseFromJSON(json: any): GetEncyclopediaInfo200Response {
    return GetEncyclopediaInfo200ResponseFromJSONTyped(json, false);
}

export function GetEncyclopediaInfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEncyclopediaInfo200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfEncyclopediaInfoError(json)) {
        return EncyclopediaInfoErrorFromJSONTyped(json, true);
    }
    if (instanceOfEncyclopediaInfoOk(json)) {
        return EncyclopediaInfoOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetEncyclopediaInfo200ResponseToJSON(json: any): any {
    return GetEncyclopediaInfo200ResponseToJSONTyped(json, false);
}

export function GetEncyclopediaInfo200ResponseToJSONTyped(value?: GetEncyclopediaInfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfEncyclopediaInfoError(value)) {
        return EncyclopediaInfoErrorToJSON(value as EncyclopediaInfoError);
    }
    if (instanceOfEncyclopediaInfoOk(value)) {
        return EncyclopediaInfoOkToJSON(value as EncyclopediaInfoOk);
    }

    return {};
}

