/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GlobalmapEventaccountratingsError } from './GlobalmapEventaccountratingsError.js';
import {
    instanceOfGlobalmapEventaccountratingsError,
    GlobalmapEventaccountratingsErrorFromJSON,
    GlobalmapEventaccountratingsErrorFromJSONTyped,
    GlobalmapEventaccountratingsErrorToJSON,
} from './GlobalmapEventaccountratingsError.js';
import type { GlobalmapEventaccountratingsOk } from './GlobalmapEventaccountratingsOk.js';
import {
    instanceOfGlobalmapEventaccountratingsOk,
    GlobalmapEventaccountratingsOkFromJSON,
    GlobalmapEventaccountratingsOkFromJSONTyped,
    GlobalmapEventaccountratingsOkToJSON,
} from './GlobalmapEventaccountratingsOk.js';

/**
 * @type GetGlobalmapEventaccountratings200Response
 * 
 * @export
 */
export type GetGlobalmapEventaccountratings200Response = GlobalmapEventaccountratingsError | GlobalmapEventaccountratingsOk;

export function GetGlobalmapEventaccountratings200ResponseFromJSON(json: any): GetGlobalmapEventaccountratings200Response {
    return GetGlobalmapEventaccountratings200ResponseFromJSONTyped(json, false);
}

export function GetGlobalmapEventaccountratings200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGlobalmapEventaccountratings200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfGlobalmapEventaccountratingsError(json)) {
        return GlobalmapEventaccountratingsErrorFromJSONTyped(json, true);
    }
    if (instanceOfGlobalmapEventaccountratingsOk(json)) {
        return GlobalmapEventaccountratingsOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetGlobalmapEventaccountratings200ResponseToJSON(json: any): any {
    return GetGlobalmapEventaccountratings200ResponseToJSONTyped(json, false);
}

export function GetGlobalmapEventaccountratings200ResponseToJSONTyped(value?: GetGlobalmapEventaccountratings200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfGlobalmapEventaccountratingsError(value)) {
        return GlobalmapEventaccountratingsErrorToJSON(value as GlobalmapEventaccountratingsError);
    }
    if (instanceOfGlobalmapEventaccountratingsOk(value)) {
        return GlobalmapEventaccountratingsOkToJSON(value as GlobalmapEventaccountratingsOk);
    }

    return {};
}

