/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GlobalmapFrontsError } from './GlobalmapFrontsError.js';
import {
    instanceOfGlobalmapFrontsError,
    GlobalmapFrontsErrorFromJSON,
    GlobalmapFrontsErrorFromJSONTyped,
    GlobalmapFrontsErrorToJSON,
} from './GlobalmapFrontsError.js';
import type { GlobalmapFrontsOk } from './GlobalmapFrontsOk.js';
import {
    instanceOfGlobalmapFrontsOk,
    GlobalmapFrontsOkFromJSON,
    GlobalmapFrontsOkFromJSONTyped,
    GlobalmapFrontsOkToJSON,
} from './GlobalmapFrontsOk.js';

/**
 * @type GetGlobalmapFronts200Response
 * 
 * @export
 */
export type GetGlobalmapFronts200Response = GlobalmapFrontsError | GlobalmapFrontsOk;

export function GetGlobalmapFronts200ResponseFromJSON(json: any): GetGlobalmapFronts200Response {
    return GetGlobalmapFronts200ResponseFromJSONTyped(json, false);
}

export function GetGlobalmapFronts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGlobalmapFronts200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfGlobalmapFrontsError(json)) {
        return GlobalmapFrontsErrorFromJSONTyped(json, true);
    }
    if (instanceOfGlobalmapFrontsOk(json)) {
        return GlobalmapFrontsOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetGlobalmapFronts200ResponseToJSON(json: any): any {
    return GetGlobalmapFronts200ResponseToJSONTyped(json, false);
}

export function GetGlobalmapFronts200ResponseToJSONTyped(value?: GetGlobalmapFronts200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfGlobalmapFrontsError(value)) {
        return GlobalmapFrontsErrorToJSON(value as GlobalmapFrontsError);
    }
    if (instanceOfGlobalmapFrontsOk(value)) {
        return GlobalmapFrontsOkToJSON(value as GlobalmapFrontsOk);
    }

    return {};
}

