/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GlobalmapEventsMeta
 */
export interface GlobalmapEventsMeta {
    /**
     * 
     * @type {number}
     * @memberof GlobalmapEventsMeta
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof GlobalmapEventsMeta
     */
    pageTotal: number;
    /**
     * 
     * @type {number}
     * @memberof GlobalmapEventsMeta
     */
    page: number;
}

/**
 * Check if a given object implements the GlobalmapEventsMeta interface.
 */
export function instanceOfGlobalmapEventsMeta(value: object): value is GlobalmapEventsMeta {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('pageTotal' in value) || value['pageTotal'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    return true;
}

export function GlobalmapEventsMetaFromJSON(json: any): GlobalmapEventsMeta {
    return GlobalmapEventsMetaFromJSONTyped(json, false);
}

export function GlobalmapEventsMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapEventsMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'pageTotal': json['page_total'],
        'page': json['page'],
    };
}

export function GlobalmapEventsMetaToJSON(json: any): GlobalmapEventsMeta {
    return GlobalmapEventsMetaToJSONTyped(json, false);
}

export function GlobalmapEventsMetaToJSONTyped(value?: GlobalmapEventsMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'page_total': value['pageTotal'],
        'page': value['page'],
    };
}

