/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GlobalmapSeasonaccountinfoDataValueSeasonsValueItem
 */
export interface GlobalmapSeasonaccountinfoDataValueSeasonsValueItem {
    /**
     * Account ID
     * @type {number}
     * @memberof GlobalmapSeasonaccountinfoDataValueSeasonsValueItem
     */
    account_id: number;
    /**
     * Award level
     * @type {string}
     * @memberof GlobalmapSeasonaccountinfoDataValueSeasonsValueItem
     */
    award_level: string | null;
    /**
     * Battles fought for current clan
     * @type {number}
     * @memberof GlobalmapSeasonaccountinfoDataValueSeasonsValueItem
     */
    battles: number | null;
    /**
     * Battles to fight in a current clan to get clan award for the season
     * @type {number}
     * @memberof GlobalmapSeasonaccountinfoDataValueSeasonsValueItem
     */
    battles_to_award: number;
    /**
     * Clan ID
     * @type {number}
     * @memberof GlobalmapSeasonaccountinfoDataValueSeasonsValueItem
     */
    clan_id: number;
    /**
     * Clan rating
     * @type {number}
     * @memberof GlobalmapSeasonaccountinfoDataValueSeasonsValueItem
     */
    clan_rank: number | null;
    /**
     * Season ID
     * @type {string}
     * @memberof GlobalmapSeasonaccountinfoDataValueSeasonsValueItem
     */
    season_id: string;
    /**
     * Vehicle Tier
     * @type {number}
     * @memberof GlobalmapSeasonaccountinfoDataValueSeasonsValueItem
     */
    vehicle_level: number;
    /**
     * Date when account data were updated
     * @type {number}
     * @memberof GlobalmapSeasonaccountinfoDataValueSeasonsValueItem
     */
    updated_at: number | null;
}

/**
 * Check if a given object implements the GlobalmapSeasonaccountinfoDataValueSeasonsValueItem interface.
 */
export function instanceOfGlobalmapSeasonaccountinfoDataValueSeasonsValueItem(value: object): value is GlobalmapSeasonaccountinfoDataValueSeasonsValueItem {
    if (!('account_id' in value) || value['account_id'] === undefined) return false;
    if (!('award_level' in value) || value['award_level'] === undefined) return false;
    if (!('battles' in value) || value['battles'] === undefined) return false;
    if (!('battles_to_award' in value) || value['battles_to_award'] === undefined) return false;
    if (!('clan_id' in value) || value['clan_id'] === undefined) return false;
    if (!('clan_rank' in value) || value['clan_rank'] === undefined) return false;
    if (!('season_id' in value) || value['season_id'] === undefined) return false;
    if (!('vehicle_level' in value) || value['vehicle_level'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    return true;
}

export function GlobalmapSeasonaccountinfoDataValueSeasonsValueItemFromJSON(json: any): GlobalmapSeasonaccountinfoDataValueSeasonsValueItem {
    return GlobalmapSeasonaccountinfoDataValueSeasonsValueItemFromJSONTyped(json, false);
}

export function GlobalmapSeasonaccountinfoDataValueSeasonsValueItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapSeasonaccountinfoDataValueSeasonsValueItem {
    if (json == null) {
        return json;
    }
    return {
        
        'account_id': json['account_id'],
        'award_level': json['award_level'],
        'battles': json['battles'],
        'battles_to_award': json['battles_to_award'],
        'clan_id': json['clan_id'],
        'clan_rank': json['clan_rank'],
        'season_id': json['season_id'],
        'vehicle_level': json['vehicle_level'],
        'updated_at': json['updated_at'],
    };
}

export function GlobalmapSeasonaccountinfoDataValueSeasonsValueItemToJSON(json: any): GlobalmapSeasonaccountinfoDataValueSeasonsValueItem {
    return GlobalmapSeasonaccountinfoDataValueSeasonsValueItemToJSONTyped(json, false);
}

export function GlobalmapSeasonaccountinfoDataValueSeasonsValueItemToJSONTyped(value?: GlobalmapSeasonaccountinfoDataValueSeasonsValueItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['account_id'],
        'award_level': value['award_level'],
        'battles': value['battles'],
        'battles_to_award': value['battles_to_award'],
        'clan_id': value['clan_id'],
        'clan_rank': value['clan_rank'],
        'season_id': value['season_id'],
        'vehicle_level': value['vehicle_level'],
        'updated_at': value['updated_at'],
    };
}

export const GlobalmapSeasonaccountinfoDataValueSeasonsValueItemPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

