/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GlobalmapInfo
 */
export interface GlobalmapInfo {
    /**
     * Map status: active, frozen, turn_calculation_in_progress
     * @type {string}
     * @memberof GlobalmapInfo
     */
    state: string;
    /**
     * Number of last calculated turn
     * @type {number}
     * @memberof GlobalmapInfo
     */
    lastTurn: number;
    /**
     * Creation time of the last calculated turn in UTC
     * @type {number}
     * @memberof GlobalmapInfo
     */
    lastTurnCreatedAt: number;
    /**
     * Calculation time of the last turn in UTC
     * @type {number}
     * @memberof GlobalmapInfo
     */
    lastTurnCalculatedAt: number;
}

/**
 * Check if a given object implements the GlobalmapInfo interface.
 */
export function instanceOfGlobalmapInfo(value: object): value is GlobalmapInfo {
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('lastTurn' in value) || value['lastTurn'] === undefined) return false;
    if (!('lastTurnCreatedAt' in value) || value['lastTurnCreatedAt'] === undefined) return false;
    if (!('lastTurnCalculatedAt' in value) || value['lastTurnCalculatedAt'] === undefined) return false;
    return true;
}

export function GlobalmapInfoFromJSON(json: any): GlobalmapInfo {
    return GlobalmapInfoFromJSONTyped(json, false);
}

export function GlobalmapInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'],
        'lastTurn': json['last_turn'],
        'lastTurnCreatedAt': json['last_turn_created_at'],
        'lastTurnCalculatedAt': json['last_turn_calculated_at'],
    };
}

export function GlobalmapInfoToJSON(json: any): GlobalmapInfo {
    return GlobalmapInfoToJSONTyped(json, false);
}

export function GlobalmapInfoToJSONTyped(value?: GlobalmapInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': value['state'],
        'last_turn': value['lastTurn'],
        'last_turn_created_at': value['lastTurnCreatedAt'],
        'last_turn_calculated_at': value['lastTurnCalculatedAt'],
    };
}

