/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GlobalmapEventaccountratingneighborsItem
 */
export interface GlobalmapEventaccountratingneighborsItem {
    /**
     * Event ID
     * @type {string}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    eventId: string;
    /**
     * Player account ID
     * @type {number}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    accountId: number;
    /**
     * Clan ID
     * @type {number}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    clanId: number;
    /**
     * Clan rating
     * @type {number}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    clanRank: number;
    /**
     * Battles fought for current clan
     * @type {number}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    battles: number;
    /**
     * Battles to fight in a current clan to get clan award for the season
     * @type {number}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    battlesToAward: number;
    /**
     * Award level
     * @type {string}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    awardLevel: string;
    /**
     * Date when account data were updated
     * @type {number}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    updatedAt: number;
    /**
     * Total Fame Points
     * @type {number}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    famePoints: number;
    /**
     * Amount of Fame Points needed to improve personal award
     * @type {number}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    famePointsToImproveAward: number;
    /**
     * Front ID
     * @type {string}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    frontId: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    url: string | null;
    /**
     * Current rating
     * @type {number}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    rank: number;
    /**
     * Rating changes during previous turn
     * @type {number}
     * @memberof GlobalmapEventaccountratingneighborsItem
     */
    rankDelta: number;
}

/**
 * Check if a given object implements the GlobalmapEventaccountratingneighborsItem interface.
 */
export function instanceOfGlobalmapEventaccountratingneighborsItem(value: object): value is GlobalmapEventaccountratingneighborsItem {
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('clanId' in value) || value['clanId'] === undefined) return false;
    if (!('clanRank' in value) || value['clanRank'] === undefined) return false;
    if (!('battles' in value) || value['battles'] === undefined) return false;
    if (!('battlesToAward' in value) || value['battlesToAward'] === undefined) return false;
    if (!('awardLevel' in value) || value['awardLevel'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('famePoints' in value) || value['famePoints'] === undefined) return false;
    if (!('famePointsToImproveAward' in value) || value['famePointsToImproveAward'] === undefined) return false;
    if (!('frontId' in value) || value['frontId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if (!('rankDelta' in value) || value['rankDelta'] === undefined) return false;
    return true;
}

export function GlobalmapEventaccountratingneighborsItemFromJSON(json: any): GlobalmapEventaccountratingneighborsItem {
    return GlobalmapEventaccountratingneighborsItemFromJSONTyped(json, false);
}

export function GlobalmapEventaccountratingneighborsItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapEventaccountratingneighborsItem {
    if (json == null) {
        return json;
    }
    return {
        
        'eventId': json['event_id'],
        'accountId': json['account_id'],
        'clanId': json['clan_id'],
        'clanRank': json['clan_rank'],
        'battles': json['battles'],
        'battlesToAward': json['battles_to_award'],
        'awardLevel': json['award_level'],
        'updatedAt': json['updated_at'],
        'famePoints': json['fame_points'],
        'famePointsToImproveAward': json['fame_points_to_improve_award'],
        'frontId': json['front_id'],
        'url': json['url'],
        'rank': json['rank'],
        'rankDelta': json['rank_delta'],
    };
}

export function GlobalmapEventaccountratingneighborsItemToJSON(json: any): GlobalmapEventaccountratingneighborsItem {
    return GlobalmapEventaccountratingneighborsItemToJSONTyped(json, false);
}

export function GlobalmapEventaccountratingneighborsItemToJSONTyped(value?: GlobalmapEventaccountratingneighborsItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': value['eventId'],
        'account_id': value['accountId'],
        'clan_id': value['clanId'],
        'clan_rank': value['clanRank'],
        'battles': value['battles'],
        'battles_to_award': value['battlesToAward'],
        'award_level': value['awardLevel'],
        'updated_at': value['updatedAt'],
        'fame_points': value['famePoints'],
        'fame_points_to_improve_award': value['famePointsToImproveAward'],
        'front_id': value['frontId'],
        'url': value['url'],
        'rank': value['rank'],
        'rank_delta': value['rankDelta'],
    };
}

