/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GlobalmapEventclantasksError } from './GlobalmapEventclantasksError.js';
import {
    instanceOfGlobalmapEventclantasksError,
    GlobalmapEventclantasksErrorFromJSON,
    GlobalmapEventclantasksErrorFromJSONTyped,
    GlobalmapEventclantasksErrorToJSON,
} from './GlobalmapEventclantasksError.js';
import type { GlobalmapEventclantasksOk } from './GlobalmapEventclantasksOk.js';
import {
    instanceOfGlobalmapEventclantasksOk,
    GlobalmapEventclantasksOkFromJSON,
    GlobalmapEventclantasksOkFromJSONTyped,
    GlobalmapEventclantasksOkToJSON,
} from './GlobalmapEventclantasksOk.js';

/**
 * @type GlobalmapEventclantasksResponse
 * 
 * @export
 */
export type GlobalmapEventclantasksResponse = GlobalmapEventclantasksError | GlobalmapEventclantasksOk;

export function GlobalmapEventclantasksResponseFromJSON(json: any): GlobalmapEventclantasksResponse {
    return GlobalmapEventclantasksResponseFromJSONTyped(json, false);
}

export function GlobalmapEventclantasksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapEventclantasksResponse {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfGlobalmapEventclantasksError(json)) {
        return GlobalmapEventclantasksErrorFromJSONTyped(json, true);
    }
    if (instanceOfGlobalmapEventclantasksOk(json)) {
        return GlobalmapEventclantasksOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GlobalmapEventclantasksResponseToJSON(json: any): any {
    return GlobalmapEventclantasksResponseToJSONTyped(json, false);
}

export function GlobalmapEventclantasksResponseToJSONTyped(value?: GlobalmapEventclantasksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfGlobalmapEventclantasksError(value)) {
        return GlobalmapEventclantasksErrorToJSON(value as GlobalmapEventclantasksError);
    }
    if (instanceOfGlobalmapEventclantasksOk(value)) {
        return GlobalmapEventclantasksOkToJSON(value as GlobalmapEventclantasksOk);
    }

    return {};
}

