/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AccountListErrorErrorOneOf3 } from './AccountListErrorErrorOneOf3.js';
import {
    AccountListErrorErrorOneOf3FromJSON,
    AccountListErrorErrorOneOf3FromJSONTyped,
    AccountListErrorErrorOneOf3ToJSON,
    AccountListErrorErrorOneOf3ToJSONTyped,
} from './AccountListErrorErrorOneOf3.js';

/**
 * 
 * @export
 * @interface GlobalmapProvincesError
 */
export interface GlobalmapProvincesError {
    /**
     * 
     * @type {string}
     * @memberof GlobalmapProvincesError
     */
    status: GlobalmapProvincesErrorStatusEnum;
    /**
     * 
     * @type {AccountListErrorErrorOneOf3}
     * @memberof GlobalmapProvincesError
     */
    error: AccountListErrorErrorOneOf3;
}


/**
 * @export
 */
export const GlobalmapProvincesErrorStatusEnum = {
    Error: 'error'
} as const;
export type GlobalmapProvincesErrorStatusEnum = typeof GlobalmapProvincesErrorStatusEnum[keyof typeof GlobalmapProvincesErrorStatusEnum];


/**
 * Check if a given object implements the GlobalmapProvincesError interface.
 */
export function instanceOfGlobalmapProvincesError(value: object): value is GlobalmapProvincesError {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GlobalmapProvincesErrorFromJSON(json: any): GlobalmapProvincesError {
    return GlobalmapProvincesErrorFromJSONTyped(json, false);
}

export function GlobalmapProvincesErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapProvincesError {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'error': AccountListErrorErrorOneOf3FromJSON(json['error']),
    };
}

export function GlobalmapProvincesErrorToJSON(json: any): GlobalmapProvincesError {
    return GlobalmapProvincesErrorToJSONTyped(json, false);
}

export function GlobalmapProvincesErrorToJSONTyped(value?: GlobalmapProvincesError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'error': AccountListErrorErrorOneOf3ToJSON(value['error']),
    };
}

