/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GlobalmapEventclaninfoValueEventsValueItem } from './GlobalmapEventclaninfoValueEventsValueItem.js';
import {
    GlobalmapEventclaninfoValueEventsValueItemFromJSON,
    GlobalmapEventclaninfoValueEventsValueItemFromJSONTyped,
    GlobalmapEventclaninfoValueEventsValueItemToJSON,
    GlobalmapEventclaninfoValueEventsValueItemToJSONTyped,
} from './GlobalmapEventclaninfoValueEventsValueItem.js';

/**
 * 
 * @export
 * @interface GlobalmapEventclaninfoValue
 */
export interface GlobalmapEventclaninfoValue {
    /**
     * 
     * @type {{ [key: string]: Array<GlobalmapEventclaninfoValueEventsValueItem>; }}
     * @memberof GlobalmapEventclaninfoValue
     */
    events: { [key: string]: Array<GlobalmapEventclaninfoValueEventsValueItem>; };
}

/**
 * Check if a given object implements the GlobalmapEventclaninfoValue interface.
 */
export function instanceOfGlobalmapEventclaninfoValue(value: object): value is GlobalmapEventclaninfoValue {
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function GlobalmapEventclaninfoValueFromJSON(json: any): GlobalmapEventclaninfoValue {
    return GlobalmapEventclaninfoValueFromJSONTyped(json, false);
}

export function GlobalmapEventclaninfoValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapEventclaninfoValue {
    if (json == null) {
        return json;
    }
    return {
        
        'events': json['events'],
    };
}

export function GlobalmapEventclaninfoValueToJSON(json: any): GlobalmapEventclaninfoValue {
    return GlobalmapEventclaninfoValueToJSONTyped(json, false);
}

export function GlobalmapEventclaninfoValueToJSONTyped(value?: GlobalmapEventclaninfoValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': value['events'],
    };
}

