/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GlobalmapEventaccountratingneighborsDataItem } from './GlobalmapEventaccountratingneighborsDataItem.js';
import {
    GlobalmapEventaccountratingneighborsDataItemFromJSON,
    GlobalmapEventaccountratingneighborsDataItemFromJSONTyped,
    GlobalmapEventaccountratingneighborsDataItemToJSON,
    GlobalmapEventaccountratingneighborsDataItemToJSONTyped,
} from './GlobalmapEventaccountratingneighborsDataItem.js';
import type { GlobalmapEventaccountratingneighborsMeta } from './GlobalmapEventaccountratingneighborsMeta.js';
import {
    GlobalmapEventaccountratingneighborsMetaFromJSON,
    GlobalmapEventaccountratingneighborsMetaFromJSONTyped,
    GlobalmapEventaccountratingneighborsMetaToJSON,
    GlobalmapEventaccountratingneighborsMetaToJSONTyped,
} from './GlobalmapEventaccountratingneighborsMeta.js';

/**
 * 
 * @export
 * @interface GlobalmapEventaccountratingneighborsOk
 */
export interface GlobalmapEventaccountratingneighborsOk {
    /**
     * 
     * @type {string}
     * @memberof GlobalmapEventaccountratingneighborsOk
     */
    status: GlobalmapEventaccountratingneighborsOkStatusEnum;
    /**
     * 
     * @type {GlobalmapEventaccountratingneighborsMeta}
     * @memberof GlobalmapEventaccountratingneighborsOk
     */
    meta: GlobalmapEventaccountratingneighborsMeta;
    /**
     * 
     * @type {Array<GlobalmapEventaccountratingneighborsDataItem>}
     * @memberof GlobalmapEventaccountratingneighborsOk
     */
    data: Array<GlobalmapEventaccountratingneighborsDataItem>;
}

/**
* @export
* @enum {string}
*/
export enum GlobalmapEventaccountratingneighborsOkStatusEnum {
    Ok = 'ok'
}


/**
 * Check if a given object implements the GlobalmapEventaccountratingneighborsOk interface.
 */
export function instanceOfGlobalmapEventaccountratingneighborsOk(value: object): value is GlobalmapEventaccountratingneighborsOk {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GlobalmapEventaccountratingneighborsOkFromJSON(json: any): GlobalmapEventaccountratingneighborsOk {
    return GlobalmapEventaccountratingneighborsOkFromJSONTyped(json, false);
}

export function GlobalmapEventaccountratingneighborsOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapEventaccountratingneighborsOk {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'meta': GlobalmapEventaccountratingneighborsMetaFromJSON(json['meta']),
        'data': ((json['data'] as Array<any>).map(GlobalmapEventaccountratingneighborsDataItemFromJSON)),
    };
}

export function GlobalmapEventaccountratingneighborsOkToJSON(json: any): GlobalmapEventaccountratingneighborsOk {
    return GlobalmapEventaccountratingneighborsOkToJSONTyped(json, false);
}

export function GlobalmapEventaccountratingneighborsOkToJSONTyped(value?: GlobalmapEventaccountratingneighborsOk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'meta': GlobalmapEventaccountratingneighborsMetaToJSON(value['meta']),
        'data': ((value['data'] as Array<any>).map(GlobalmapEventaccountratingneighborsDataItemToJSON)),
    };
}

export const GlobalmapEventaccountratingneighborsOkPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

