/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GlobalmapSeasonratingneighborsError } from './GlobalmapSeasonratingneighborsError.js';
import {
    instanceOfGlobalmapSeasonratingneighborsError,
    GlobalmapSeasonratingneighborsErrorFromJSON,
    GlobalmapSeasonratingneighborsErrorFromJSONTyped,
    GlobalmapSeasonratingneighborsErrorToJSON,
} from './GlobalmapSeasonratingneighborsError.js';
import type { GlobalmapSeasonratingneighborsOk } from './GlobalmapSeasonratingneighborsOk.js';
import {
    instanceOfGlobalmapSeasonratingneighborsOk,
    GlobalmapSeasonratingneighborsOkFromJSON,
    GlobalmapSeasonratingneighborsOkFromJSONTyped,
    GlobalmapSeasonratingneighborsOkToJSON,
} from './GlobalmapSeasonratingneighborsOk.js';

/**
 * @type GlobalmapSeasonratingneighborsResponse
 * 
 * @export
 */
export type GlobalmapSeasonratingneighborsResponse = GlobalmapSeasonratingneighborsError | GlobalmapSeasonratingneighborsOk;

export function GlobalmapSeasonratingneighborsResponseFromJSON(json: any): GlobalmapSeasonratingneighborsResponse {
    return GlobalmapSeasonratingneighborsResponseFromJSONTyped(json, false);
}

export function GlobalmapSeasonratingneighborsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapSeasonratingneighborsResponse {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfGlobalmapSeasonratingneighborsError(json)) {
        return GlobalmapSeasonratingneighborsErrorFromJSONTyped(json, true);
    }
    if (instanceOfGlobalmapSeasonratingneighborsOk(json)) {
        return GlobalmapSeasonratingneighborsOkFromJSONTyped(json, true);
    }

    return {} as any;
}

export function GlobalmapSeasonratingneighborsResponseToJSON(json: any): any {
    return GlobalmapSeasonratingneighborsResponseToJSONTyped(json, false);
}

export function GlobalmapSeasonratingneighborsResponseToJSONTyped(value?: GlobalmapSeasonratingneighborsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfGlobalmapSeasonratingneighborsError(value)) {
        return GlobalmapSeasonratingneighborsErrorToJSON(value as GlobalmapSeasonratingneighborsError);
    }
    if (instanceOfGlobalmapSeasonratingneighborsOk(value)) {
        return GlobalmapSeasonratingneighborsOkToJSON(value as GlobalmapSeasonratingneighborsOk);
    }

    return {};
}

