/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GlobalmapEventsErrorError } from './GlobalmapEventsErrorError.js';
import {
    GlobalmapEventsErrorErrorFromJSON,
    GlobalmapEventsErrorErrorFromJSONTyped,
    GlobalmapEventsErrorErrorToJSON,
    GlobalmapEventsErrorErrorToJSONTyped,
} from './GlobalmapEventsErrorError.js';

/**
 * 
 * @export
 * @interface GlobalmapEventsError
 */
export interface GlobalmapEventsError {
    /**
     * 
     * @type {string}
     * @memberof GlobalmapEventsError
     */
    status: GlobalmapEventsErrorStatusEnum;
    /**
     * 
     * @type {GlobalmapEventsErrorError}
     * @memberof GlobalmapEventsError
     */
    error: GlobalmapEventsErrorError;
}

/**
* @export
* @enum {string}
*/
export enum GlobalmapEventsErrorStatusEnum {
    Error = 'error'
}


/**
 * Check if a given object implements the GlobalmapEventsError interface.
 */
export function instanceOfGlobalmapEventsError(value: object): value is GlobalmapEventsError {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GlobalmapEventsErrorFromJSON(json: any): GlobalmapEventsError {
    return GlobalmapEventsErrorFromJSONTyped(json, false);
}

export function GlobalmapEventsErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapEventsError {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'error': GlobalmapEventsErrorErrorFromJSON(json['error']),
    };
}

export function GlobalmapEventsErrorToJSON(json: any): GlobalmapEventsError {
    return GlobalmapEventsErrorToJSONTyped(json, false);
}

export function GlobalmapEventsErrorToJSONTyped(value?: GlobalmapEventsError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'error': GlobalmapEventsErrorErrorToJSON(value['error']),
    };
}

export const GlobalmapEventsErrorPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

