/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Clan rating on the Global Map
 * @export
 * @interface GlobalmapClaninfoDataValueRatings
 */
export interface GlobalmapClaninfoDataValueRatings {
    /**
     * Ratings update time
     * @type {number}
     * @memberof GlobalmapClaninfoDataValueRatings
     */
    updated_at: number;
    /**
     * Clan Elo rating in Medium division
     * @type {number}
     * @memberof GlobalmapClaninfoDataValueRatings
     */
    elo_6: number;
    /**
     * Clan Elo rating in Champion division
     * @type {number}
     * @memberof GlobalmapClaninfoDataValueRatings
     */
    elo_8: number;
    /**
     * Clan Elo rating in Absolute division
     * @type {number}
     * @memberof GlobalmapClaninfoDataValueRatings
     */
    elo_10: number;
}

/**
 * Check if a given object implements the GlobalmapClaninfoDataValueRatings interface.
 */
export function instanceOfGlobalmapClaninfoDataValueRatings(value: object): value is GlobalmapClaninfoDataValueRatings {
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    if (!('elo_6' in value) || value['elo_6'] === undefined) return false;
    if (!('elo_8' in value) || value['elo_8'] === undefined) return false;
    if (!('elo_10' in value) || value['elo_10'] === undefined) return false;
    return true;
}

export function GlobalmapClaninfoDataValueRatingsFromJSON(json: any): GlobalmapClaninfoDataValueRatings {
    return GlobalmapClaninfoDataValueRatingsFromJSONTyped(json, false);
}

export function GlobalmapClaninfoDataValueRatingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapClaninfoDataValueRatings {
    if (json == null) {
        return json;
    }
    return {
        
        'updated_at': json['updated_at'],
        'elo_6': json['elo_6'],
        'elo_8': json['elo_8'],
        'elo_10': json['elo_10'],
    };
}

export function GlobalmapClaninfoDataValueRatingsToJSON(json: any): GlobalmapClaninfoDataValueRatings {
    return GlobalmapClaninfoDataValueRatingsToJSONTyped(json, false);
}

export function GlobalmapClaninfoDataValueRatingsToJSONTyped(value?: GlobalmapClaninfoDataValueRatings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'updated_at': value['updated_at'],
        'elo_6': value['elo_6'],
        'elo_8': value['elo_8'],
        'elo_10': value['elo_10'],
    };
}

export const GlobalmapClaninfoDataValueRatingsPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

