/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GlobalmapEventclaninfoMeta } from './GlobalmapEventclaninfoMeta.js';
import {
    GlobalmapEventclaninfoMetaFromJSON,
    GlobalmapEventclaninfoMetaFromJSONTyped,
    GlobalmapEventclaninfoMetaToJSON,
    GlobalmapEventclaninfoMetaToJSONTyped,
} from './GlobalmapEventclaninfoMeta.js';
import type { GlobalmapEventclaninfoDataValue } from './GlobalmapEventclaninfoDataValue.js';
import {
    GlobalmapEventclaninfoDataValueFromJSON,
    GlobalmapEventclaninfoDataValueFromJSONTyped,
    GlobalmapEventclaninfoDataValueToJSON,
    GlobalmapEventclaninfoDataValueToJSONTyped,
} from './GlobalmapEventclaninfoDataValue.js';

/**
 * 
 * @export
 * @interface GlobalmapEventclaninfoOk
 */
export interface GlobalmapEventclaninfoOk {
    /**
     * 
     * @type {string}
     * @memberof GlobalmapEventclaninfoOk
     */
    status: GlobalmapEventclaninfoOkStatusEnum;
    /**
     * 
     * @type {GlobalmapEventclaninfoMeta}
     * @memberof GlobalmapEventclaninfoOk
     */
    meta: GlobalmapEventclaninfoMeta;
    /**
     * 
     * @type {{ [key: string]: GlobalmapEventclaninfoDataValue | undefined; }}
     * @memberof GlobalmapEventclaninfoOk
     */
    data: { [key: string]: GlobalmapEventclaninfoDataValue | undefined; };
}

/**
* @export
* @enum {string}
*/
export enum GlobalmapEventclaninfoOkStatusEnum {
    Ok = 'ok'
}


/**
 * Check if a given object implements the GlobalmapEventclaninfoOk interface.
 */
export function instanceOfGlobalmapEventclaninfoOk(value: object): value is GlobalmapEventclaninfoOk {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GlobalmapEventclaninfoOkFromJSON(json: any): GlobalmapEventclaninfoOk {
    return GlobalmapEventclaninfoOkFromJSONTyped(json, false);
}

export function GlobalmapEventclaninfoOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapEventclaninfoOk {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'meta': GlobalmapEventclaninfoMetaFromJSON(json['meta']),
        'data': (mapValues(json['data'], GlobalmapEventclaninfoDataValueFromJSON)),
    };
}

export function GlobalmapEventclaninfoOkToJSON(json: any): GlobalmapEventclaninfoOk {
    return GlobalmapEventclaninfoOkToJSONTyped(json, false);
}

export function GlobalmapEventclaninfoOkToJSONTyped(value?: GlobalmapEventclaninfoOk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'meta': GlobalmapEventclaninfoMetaToJSON(value['meta']),
        'data': (mapValues(value['data'], GlobalmapEventclaninfoDataValueToJSON)),
    };
}

export const GlobalmapEventclaninfoOkPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

