/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GlobalmapEventsErrorError } from './GlobalmapEventsErrorError.js';
import {
    GlobalmapEventsErrorErrorFromJSON,
    GlobalmapEventsErrorErrorFromJSONTyped,
    GlobalmapEventsErrorErrorToJSON,
    GlobalmapEventsErrorErrorToJSONTyped,
} from './GlobalmapEventsErrorError.js';

/**
 * 
 * @export
 * @interface GlobalmapEventclaninfoError
 */
export interface GlobalmapEventclaninfoError {
    /**
     * 
     * @type {string}
     * @memberof GlobalmapEventclaninfoError
     */
    status: GlobalmapEventclaninfoErrorStatusEnum;
    /**
     * 
     * @type {GlobalmapEventsErrorError}
     * @memberof GlobalmapEventclaninfoError
     */
    error: GlobalmapEventsErrorError;
}

/**
* @export
* @enum {string}
*/
export enum GlobalmapEventclaninfoErrorStatusEnum {
    Error = 'error'
}


/**
 * Check if a given object implements the GlobalmapEventclaninfoError interface.
 */
export function instanceOfGlobalmapEventclaninfoError(value: object): value is GlobalmapEventclaninfoError {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GlobalmapEventclaninfoErrorFromJSON(json: any): GlobalmapEventclaninfoError {
    return GlobalmapEventclaninfoErrorFromJSONTyped(json, false);
}

export function GlobalmapEventclaninfoErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapEventclaninfoError {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'error': GlobalmapEventsErrorErrorFromJSON(json['error']),
    };
}

export function GlobalmapEventclaninfoErrorToJSON(json: any): GlobalmapEventclaninfoError {
    return GlobalmapEventclaninfoErrorToJSONTyped(json, false);
}

export function GlobalmapEventclaninfoErrorToJSONTyped(value?: GlobalmapEventclaninfoError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'error': GlobalmapEventsErrorErrorToJSON(value['error']),
    };
}

export const GlobalmapEventclaninfoErrorPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

