/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GlobalmapEventsItemFrontsItem
 */
export interface GlobalmapEventsItemFrontsItem {
    /**
     * Front ID
     * @type {string}
     * @memberof GlobalmapEventsItemFrontsItem
     */
    frontId: string;
    /**
     * Front name
     * @type {string}
     * @memberof GlobalmapEventsItemFrontsItem
     */
    frontName: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalmapEventsItemFrontsItem
     */
    url: string | null;
}

/**
 * Check if a given object implements the GlobalmapEventsItemFrontsItem interface.
 */
export function instanceOfGlobalmapEventsItemFrontsItem(value: object): value is GlobalmapEventsItemFrontsItem {
    if (!('frontId' in value) || value['frontId'] === undefined) return false;
    if (!('frontName' in value) || value['frontName'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function GlobalmapEventsItemFrontsItemFromJSON(json: any): GlobalmapEventsItemFrontsItem {
    return GlobalmapEventsItemFrontsItemFromJSONTyped(json, false);
}

export function GlobalmapEventsItemFrontsItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapEventsItemFrontsItem {
    if (json == null) {
        return json;
    }
    return {
        
        'frontId': json['front_id'],
        'frontName': json['front_name'],
        'url': json['url'],
    };
}

export function GlobalmapEventsItemFrontsItemToJSON(json: any): GlobalmapEventsItemFrontsItem {
    return GlobalmapEventsItemFrontsItemToJSONTyped(json, false);
}

export function GlobalmapEventsItemFrontsItemToJSONTyped(value?: GlobalmapEventsItemFrontsItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'front_id': value['frontId'],
        'front_name': value['frontName'],
        'url': value['url'],
    };
}

