/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Account or clan ID is not specified
 * @export
 * @interface GlobalmapEventaccountinfoErrorErrorOneOf
 */
export interface GlobalmapEventaccountinfoErrorErrorOneOf {
    /**
     * 
     * @type {number}
     * @memberof GlobalmapEventaccountinfoErrorErrorOneOf
     */
    code: GlobalmapEventaccountinfoErrorErrorOneOfCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof GlobalmapEventaccountinfoErrorErrorOneOf
     */
    message: GlobalmapEventaccountinfoErrorErrorOneOfMessageEnum;
    /**
     * 
     * @type {string}
     * @memberof GlobalmapEventaccountinfoErrorErrorOneOf
     */
    field: string | null;
    /**
     * 
     * @type {string}
     * @memberof GlobalmapEventaccountinfoErrorErrorOneOf
     */
    value: string | null;
}

/**
* @export
* @enum {string}
*/
export enum GlobalmapEventaccountinfoErrorErrorOneOfCodeEnum {
    NUMBER_402 = 402
}
/**
* @export
* @enum {string}
*/
export enum GlobalmapEventaccountinfoErrorErrorOneOfMessageEnum {
    AccountIdOrClanIdNotSpecified = 'ACCOUNT_ID_OR_CLAN_ID_NOT_SPECIFIED'
}


/**
 * Check if a given object implements the GlobalmapEventaccountinfoErrorErrorOneOf interface.
 */
export function instanceOfGlobalmapEventaccountinfoErrorErrorOneOf(value: object): value is GlobalmapEventaccountinfoErrorErrorOneOf {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function GlobalmapEventaccountinfoErrorErrorOneOfFromJSON(json: any): GlobalmapEventaccountinfoErrorErrorOneOf {
    return GlobalmapEventaccountinfoErrorErrorOneOfFromJSONTyped(json, false);
}

export function GlobalmapEventaccountinfoErrorErrorOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalmapEventaccountinfoErrorErrorOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'field': json['field'],
        'value': json['value'],
    };
}

export function GlobalmapEventaccountinfoErrorErrorOneOfToJSON(json: any): GlobalmapEventaccountinfoErrorErrorOneOf {
    return GlobalmapEventaccountinfoErrorErrorOneOfToJSONTyped(json, false);
}

export function GlobalmapEventaccountinfoErrorErrorOneOfToJSONTyped(value?: GlobalmapEventaccountinfoErrorErrorOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'field': value['field'],
        'value': value['value'],
    };
}

export const GlobalmapEventaccountinfoErrorErrorOneOfPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

