/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface StrongholdActivateclanreserveData
 */
export interface StrongholdActivateclanreserveData {
    /**
     * Activation time of a clan Reserve
     * @type {number}
     * @memberof StrongholdActivateclanreserveData
     */
    activated_at: number;
}

/**
 * Check if a given object implements the StrongholdActivateclanreserveData interface.
 */
export function instanceOfStrongholdActivateclanreserveData(value: object): value is StrongholdActivateclanreserveData {
    if (!('activated_at' in value) || value['activated_at'] === undefined) return false;
    return true;
}

export function StrongholdActivateclanreserveDataFromJSON(json: any): StrongholdActivateclanreserveData {
    return StrongholdActivateclanreserveDataFromJSONTyped(json, false);
}

export function StrongholdActivateclanreserveDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrongholdActivateclanreserveData {
    if (json == null) {
        return json;
    }
    return {
        
        'activated_at': json['activated_at'],
    };
}

export function StrongholdActivateclanreserveDataToJSON(json: any): StrongholdActivateclanreserveData {
    return StrongholdActivateclanreserveDataToJSONTyped(json, false);
}

export function StrongholdActivateclanreserveDataToJSONTyped(value?: StrongholdActivateclanreserveData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activated_at': value['activated_at'],
    };
}

export const StrongholdActivateclanreserveDataPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

