/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Account is not in clan
 * @export
 * @interface StrongholdClanreservesErrorErrorOneOf
 */
export interface StrongholdClanreservesErrorErrorOneOf {
    /**
     * 
     * @type {number}
     * @memberof StrongholdClanreservesErrorErrorOneOf
     */
    code: StrongholdClanreservesErrorErrorOneOfCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof StrongholdClanreservesErrorErrorOneOf
     */
    message: StrongholdClanreservesErrorErrorOneOfMessageEnum;
    /**
     * 
     * @type {string}
     * @memberof StrongholdClanreservesErrorErrorOneOf
     */
    field: string | null;
    /**
     * 
     * @type {string}
     * @memberof StrongholdClanreservesErrorErrorOneOf
     */
    value: string | null;
}


/**
 * @export
 */
export const StrongholdClanreservesErrorErrorOneOfCodeEnum = {
    NUMBER_409: 409
} as const;
export type StrongholdClanreservesErrorErrorOneOfCodeEnum = typeof StrongholdClanreservesErrorErrorOneOfCodeEnum[keyof typeof StrongholdClanreservesErrorErrorOneOfCodeEnum];

/**
 * @export
 */
export const StrongholdClanreservesErrorErrorOneOfMessageEnum = {
    AccountNotInClan: 'ACCOUNT_NOT_IN_CLAN'
} as const;
export type StrongholdClanreservesErrorErrorOneOfMessageEnum = typeof StrongholdClanreservesErrorErrorOneOfMessageEnum[keyof typeof StrongholdClanreservesErrorErrorOneOfMessageEnum];


/**
 * Check if a given object implements the StrongholdClanreservesErrorErrorOneOf interface.
 */
export function instanceOfStrongholdClanreservesErrorErrorOneOf(value: object): value is StrongholdClanreservesErrorErrorOneOf {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function StrongholdClanreservesErrorErrorOneOfFromJSON(json: any): StrongholdClanreservesErrorErrorOneOf {
    return StrongholdClanreservesErrorErrorOneOfFromJSONTyped(json, false);
}

export function StrongholdClanreservesErrorErrorOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrongholdClanreservesErrorErrorOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'field': json['field'],
        'value': json['value'],
    };
}

export function StrongholdClanreservesErrorErrorOneOfToJSON(json: any): StrongholdClanreservesErrorErrorOneOf {
    return StrongholdClanreservesErrorErrorOneOfToJSONTyped(json, false);
}

export function StrongholdClanreservesErrorErrorOneOfToJSONTyped(value?: StrongholdClanreservesErrorErrorOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'field': value['field'],
        'value': value['value'],
    };
}

