/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Overall Statistics
 * @export
 * @interface TanksStatsValueItemAll
 */
export interface TanksStatsValueItemAll {
    /**
     * Battles fought
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    battles: number;
    /**
     * Victories
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    wins: number;
    /**
     * Total experience
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    xp: number;
    /**
     * Defeats
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    losses: number;
    /**
     * Battles survived
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    survivedBattles: number;
    /**
     * Damage received
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    damageReceived: number;
    /**
     * Damage caused
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    damageDealt: number;
    /**
     * Enemies spotted
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    spotted: number;
    /**
     * Shots fired
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    shots: number;
    /**
     * Hits
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    hits: number;
    /**
     * Vehicles destroyed
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    frags: number;
    /**
     * Base capture points
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    capturePoints: number;
    /**
     * Base defense points
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    droppedCapturePoints: number;
    /**
     * Hit ratio
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    hitsPercents: number;
    /**
     * Draws
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    draws: number;
    /**
     * Average experience per battle
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    battleAvgXp: number;
    /**
     * Number of times an enemy was stunned by you
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    stunNumber: number;
    /**
     * Number of battles on vehicles that cause the stun effect
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    battlesOnStunningVehicles: number;
    /**
     * Damage to enemy vehicles stunned by you
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    stunAssistedDamage: number;
    /**
     * Damage dealt to the target with the actor keeping-on-track assistance
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    trackAssistedDamage: number;
    /**
     * Damage dealt to the target with the actor radio recon assistance
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    radioAssistedDamage: number;
    /**
     * Ratio of damage blocked by armor from AP, HEAT, and APCR shells to damage received from these types of shells.
     * Value is calculated starting from version 9.0.
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    tankingFactor: number;
    /**
     * Direct hits received
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    directHitsReceived: number;
    /**
     * Hits received as a result of splash damage
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    explosionHitsReceived: number;
    /**
     * Hits on enemy as a result of splash damage
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    explosionHits: number;
    /**
     * Penetrations received
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    piercingsReceived: number;
    /**
     * Penetrations
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    piercings: number;
    /**
     * Direct hits received that caused no damage
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    noDamageDirectHitsReceived: number;
    /**
     * Average damage blocked by armor per battle. Damage blocked by armor is damage received from shells (AP, HEAT and APCR) that hit a vehicle but caused no damage.
     * Value is calculated starting from version 9.0.
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    avgDamageBlocked: number;
    /**
     * Average damage upon your shooting the track
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    avgDamageAssistedTrack: number;
    /**
     * Average damage upon your spotting
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    avgDamageAssistedRadio: number;
    /**
     * Average assisted damage without stun damage.
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    avgDamageAssisted: number;
    /**
     * Average assisted stun damage.
     * @type {number}
     * @memberof TanksStatsValueItemAll
     */
    avgDamageAssistedStun: number;
}

/**
 * Check if a given object implements the TanksStatsValueItemAll interface.
 */
export function instanceOfTanksStatsValueItemAll(value: object): value is TanksStatsValueItemAll {
    if (!('battles' in value) || value['battles'] === undefined) return false;
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('xp' in value) || value['xp'] === undefined) return false;
    if (!('losses' in value) || value['losses'] === undefined) return false;
    if (!('survivedBattles' in value) || value['survivedBattles'] === undefined) return false;
    if (!('damageReceived' in value) || value['damageReceived'] === undefined) return false;
    if (!('damageDealt' in value) || value['damageDealt'] === undefined) return false;
    if (!('spotted' in value) || value['spotted'] === undefined) return false;
    if (!('shots' in value) || value['shots'] === undefined) return false;
    if (!('hits' in value) || value['hits'] === undefined) return false;
    if (!('frags' in value) || value['frags'] === undefined) return false;
    if (!('capturePoints' in value) || value['capturePoints'] === undefined) return false;
    if (!('droppedCapturePoints' in value) || value['droppedCapturePoints'] === undefined) return false;
    if (!('hitsPercents' in value) || value['hitsPercents'] === undefined) return false;
    if (!('draws' in value) || value['draws'] === undefined) return false;
    if (!('battleAvgXp' in value) || value['battleAvgXp'] === undefined) return false;
    if (!('stunNumber' in value) || value['stunNumber'] === undefined) return false;
    if (!('battlesOnStunningVehicles' in value) || value['battlesOnStunningVehicles'] === undefined) return false;
    if (!('stunAssistedDamage' in value) || value['stunAssistedDamage'] === undefined) return false;
    if (!('trackAssistedDamage' in value) || value['trackAssistedDamage'] === undefined) return false;
    if (!('radioAssistedDamage' in value) || value['radioAssistedDamage'] === undefined) return false;
    if (!('tankingFactor' in value) || value['tankingFactor'] === undefined) return false;
    if (!('directHitsReceived' in value) || value['directHitsReceived'] === undefined) return false;
    if (!('explosionHitsReceived' in value) || value['explosionHitsReceived'] === undefined) return false;
    if (!('explosionHits' in value) || value['explosionHits'] === undefined) return false;
    if (!('piercingsReceived' in value) || value['piercingsReceived'] === undefined) return false;
    if (!('piercings' in value) || value['piercings'] === undefined) return false;
    if (!('noDamageDirectHitsReceived' in value) || value['noDamageDirectHitsReceived'] === undefined) return false;
    if (!('avgDamageBlocked' in value) || value['avgDamageBlocked'] === undefined) return false;
    if (!('avgDamageAssistedTrack' in value) || value['avgDamageAssistedTrack'] === undefined) return false;
    if (!('avgDamageAssistedRadio' in value) || value['avgDamageAssistedRadio'] === undefined) return false;
    if (!('avgDamageAssisted' in value) || value['avgDamageAssisted'] === undefined) return false;
    if (!('avgDamageAssistedStun' in value) || value['avgDamageAssistedStun'] === undefined) return false;
    return true;
}

export function TanksStatsValueItemAllFromJSON(json: any): TanksStatsValueItemAll {
    return TanksStatsValueItemAllFromJSONTyped(json, false);
}

export function TanksStatsValueItemAllFromJSONTyped(json: any, ignoreDiscriminator: boolean): TanksStatsValueItemAll {
    if (json == null) {
        return json;
    }
    return {
        
        'battles': json['battles'],
        'wins': json['wins'],
        'xp': json['xp'],
        'losses': json['losses'],
        'survivedBattles': json['survived_battles'],
        'damageReceived': json['damage_received'],
        'damageDealt': json['damage_dealt'],
        'spotted': json['spotted'],
        'shots': json['shots'],
        'hits': json['hits'],
        'frags': json['frags'],
        'capturePoints': json['capture_points'],
        'droppedCapturePoints': json['dropped_capture_points'],
        'hitsPercents': json['hits_percents'],
        'draws': json['draws'],
        'battleAvgXp': json['battle_avg_xp'],
        'stunNumber': json['stun_number'],
        'battlesOnStunningVehicles': json['battles_on_stunning_vehicles'],
        'stunAssistedDamage': json['stun_assisted_damage'],
        'trackAssistedDamage': json['track_assisted_damage'],
        'radioAssistedDamage': json['radio_assisted_damage'],
        'tankingFactor': json['tanking_factor'],
        'directHitsReceived': json['direct_hits_received'],
        'explosionHitsReceived': json['explosion_hits_received'],
        'explosionHits': json['explosion_hits'],
        'piercingsReceived': json['piercings_received'],
        'piercings': json['piercings'],
        'noDamageDirectHitsReceived': json['no_damage_direct_hits_received'],
        'avgDamageBlocked': json['avg_damage_blocked'],
        'avgDamageAssistedTrack': json['avg_damage_assisted_track'],
        'avgDamageAssistedRadio': json['avg_damage_assisted_radio'],
        'avgDamageAssisted': json['avg_damage_assisted'],
        'avgDamageAssistedStun': json['avg_damage_assisted_stun'],
    };
}

export function TanksStatsValueItemAllToJSON(json: any): TanksStatsValueItemAll {
    return TanksStatsValueItemAllToJSONTyped(json, false);
}

export function TanksStatsValueItemAllToJSONTyped(value?: TanksStatsValueItemAll | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'battles': value['battles'],
        'wins': value['wins'],
        'xp': value['xp'],
        'losses': value['losses'],
        'survived_battles': value['survivedBattles'],
        'damage_received': value['damageReceived'],
        'damage_dealt': value['damageDealt'],
        'spotted': value['spotted'],
        'shots': value['shots'],
        'hits': value['hits'],
        'frags': value['frags'],
        'capture_points': value['capturePoints'],
        'dropped_capture_points': value['droppedCapturePoints'],
        'hits_percents': value['hitsPercents'],
        'draws': value['draws'],
        'battle_avg_xp': value['battleAvgXp'],
        'stun_number': value['stunNumber'],
        'battles_on_stunning_vehicles': value['battlesOnStunningVehicles'],
        'stun_assisted_damage': value['stunAssistedDamage'],
        'track_assisted_damage': value['trackAssistedDamage'],
        'radio_assisted_damage': value['radioAssistedDamage'],
        'tanking_factor': value['tankingFactor'],
        'direct_hits_received': value['directHitsReceived'],
        'explosion_hits_received': value['explosionHitsReceived'],
        'explosion_hits': value['explosionHits'],
        'piercings_received': value['piercingsReceived'],
        'piercings': value['piercings'],
        'no_damage_direct_hits_received': value['noDamageDirectHitsReceived'],
        'avg_damage_blocked': value['avgDamageBlocked'],
        'avg_damage_assisted_track': value['avgDamageAssistedTrack'],
        'avg_damage_assisted_radio': value['avgDamageAssistedRadio'],
        'avg_damage_assisted': value['avgDamageAssisted'],
        'avg_damage_assisted_stun': value['avgDamageAssistedStun'],
    };
}

