/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TanksMasteryMeta
 */
export interface TanksMasteryMeta {
    /**
     * 
     * @type {number}
     * @memberof TanksMasteryMeta
     */
    count: number;
}

/**
 * Check if a given object implements the TanksMasteryMeta interface.
 */
export function instanceOfTanksMasteryMeta(value: object): value is TanksMasteryMeta {
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function TanksMasteryMetaFromJSON(json: any): TanksMasteryMeta {
    return TanksMasteryMetaFromJSONTyped(json, false);
}

export function TanksMasteryMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TanksMasteryMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
    };
}

export function TanksMasteryMetaToJSON(json: any): TanksMasteryMeta {
    return TanksMasteryMetaToJSONTyped(json, false);
}

export function TanksMasteryMetaToJSONTyped(value?: TanksMasteryMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
    };
}

export const TanksMasteryMetaPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}

