/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface TanksAchievementsValueItem
 */
export interface TanksAchievementsValueItem {
    /**
     * Player account ID
     * @type {number}
     * @memberof TanksAchievementsValueItem
     */
    accountId: number;
    /**
     * Vehicle ID
     * @type {number}
     * @memberof TanksAchievementsValueItem
     */
    tankId: number;
    /**
     * Achievements earned
     * @type {{ [key: string]: number; }}
     * @memberof TanksAchievementsValueItem
     */
    achievements: { [key: string]: number; };
    /**
     * Current values of Achievement Series
     * @type {{ [key: string]: number; }}
     * @memberof TanksAchievementsValueItem
     */
    series: { [key: string]: number; };
    /**
     * Maximum values of achievement series
     * @type {{ [key: string]: number; }}
     * @memberof TanksAchievementsValueItem
     */
    maxSeries: { [key: string]: number; };
}

/**
 * Check if a given object implements the TanksAchievementsValueItem interface.
 */
export function instanceOfTanksAchievementsValueItem(value: object): value is TanksAchievementsValueItem {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('tankId' in value) || value['tankId'] === undefined) return false;
    if (!('achievements' in value) || value['achievements'] === undefined) return false;
    if (!('series' in value) || value['series'] === undefined) return false;
    if (!('maxSeries' in value) || value['maxSeries'] === undefined) return false;
    return true;
}

export function TanksAchievementsValueItemFromJSON(json: any): TanksAchievementsValueItem {
    return TanksAchievementsValueItemFromJSONTyped(json, false);
}

export function TanksAchievementsValueItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TanksAchievementsValueItem {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'tankId': json['tank_id'],
        'achievements': json['achievements'],
        'series': json['series'],
        'maxSeries': json['max_series'],
    };
}

export function TanksAchievementsValueItemToJSON(json: any): TanksAchievementsValueItem {
    return TanksAchievementsValueItemToJSONTyped(json, false);
}

export function TanksAchievementsValueItemToJSONTyped(value?: TanksAchievementsValueItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'tank_id': value['tankId'],
        'achievements': value['achievements'],
        'series': value['series'],
        'max_series': value['maxSeries'],
    };
}

