/* tslint:disable */
/* eslint-disable */
/**
 * World of Tanks
 * OpenAPI specification for the Wargaming.net Public API. The official Wargaming.net Public API documentation can be found at the Wargaming [Developer\'s room](https://developers.wargaming.net/).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@ace-tanker.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Team battles statistics
 * @export
 * @interface TanksStatsValueItemTeam
 */
export interface TanksStatsValueItemTeam {
    /**
     * Battles fought
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    battles: number;
    /**
     * Victories
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    wins: number;
    /**
     * Total experience
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    xp: number;
    /**
     * Defeats
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    losses: number;
    /**
     * Battles survived
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    survivedBattles: number;
    /**
     * Damage received
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    damageReceived: number;
    /**
     * Damage caused
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    damageDealt: number;
    /**
     * Enemies spotted
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    spotted: number;
    /**
     * Shots fired
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    shots: number;
    /**
     * Hits
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    hits: number;
    /**
     * Vehicles destroyed
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    frags: number;
    /**
     * Base capture points
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    capturePoints: number;
    /**
     * Base defense points
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    droppedCapturePoints: number;
    /**
     * Hit ratio
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    hitsPercents: number;
    /**
     * Draws
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    draws: number;
    /**
     * Average experience per battle
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    battleAvgXp: number;
    /**
     * Number of times an enemy was stunned by you
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    stunNumber: number;
    /**
     * Number of battles on vehicles that cause the stun effect
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    battlesOnStunningVehicles: number;
    /**
     * Damage to enemy vehicles stunned by you
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    stunAssistedDamage: number;
    /**
     * Damage dealt to the target with the actor keeping-on-track assistance
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    trackAssistedDamage: number;
    /**
     * Damage dealt to the target with the actor radio recon assistance
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    radioAssistedDamage: number;
    /**
     * Maximum destroyed in battle
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    maxFrags: number;
    /**
     * Maximum experience per battle
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    maxXp: number;
    /**
     * Maximum damage caused in a battle
     * @type {number}
     * @memberof TanksStatsValueItemTeam
     */
    maxDamage: number;
}

/**
 * Check if a given object implements the TanksStatsValueItemTeam interface.
 */
export function instanceOfTanksStatsValueItemTeam(value: object): value is TanksStatsValueItemTeam {
    if (!('battles' in value) || value['battles'] === undefined) return false;
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('xp' in value) || value['xp'] === undefined) return false;
    if (!('losses' in value) || value['losses'] === undefined) return false;
    if (!('survivedBattles' in value) || value['survivedBattles'] === undefined) return false;
    if (!('damageReceived' in value) || value['damageReceived'] === undefined) return false;
    if (!('damageDealt' in value) || value['damageDealt'] === undefined) return false;
    if (!('spotted' in value) || value['spotted'] === undefined) return false;
    if (!('shots' in value) || value['shots'] === undefined) return false;
    if (!('hits' in value) || value['hits'] === undefined) return false;
    if (!('frags' in value) || value['frags'] === undefined) return false;
    if (!('capturePoints' in value) || value['capturePoints'] === undefined) return false;
    if (!('droppedCapturePoints' in value) || value['droppedCapturePoints'] === undefined) return false;
    if (!('hitsPercents' in value) || value['hitsPercents'] === undefined) return false;
    if (!('draws' in value) || value['draws'] === undefined) return false;
    if (!('battleAvgXp' in value) || value['battleAvgXp'] === undefined) return false;
    if (!('stunNumber' in value) || value['stunNumber'] === undefined) return false;
    if (!('battlesOnStunningVehicles' in value) || value['battlesOnStunningVehicles'] === undefined) return false;
    if (!('stunAssistedDamage' in value) || value['stunAssistedDamage'] === undefined) return false;
    if (!('trackAssistedDamage' in value) || value['trackAssistedDamage'] === undefined) return false;
    if (!('radioAssistedDamage' in value) || value['radioAssistedDamage'] === undefined) return false;
    if (!('maxFrags' in value) || value['maxFrags'] === undefined) return false;
    if (!('maxXp' in value) || value['maxXp'] === undefined) return false;
    if (!('maxDamage' in value) || value['maxDamage'] === undefined) return false;
    return true;
}

export function TanksStatsValueItemTeamFromJSON(json: any): TanksStatsValueItemTeam {
    return TanksStatsValueItemTeamFromJSONTyped(json, false);
}

export function TanksStatsValueItemTeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): TanksStatsValueItemTeam {
    if (json == null) {
        return json;
    }
    return {
        
        'battles': json['battles'],
        'wins': json['wins'],
        'xp': json['xp'],
        'losses': json['losses'],
        'survivedBattles': json['survived_battles'],
        'damageReceived': json['damage_received'],
        'damageDealt': json['damage_dealt'],
        'spotted': json['spotted'],
        'shots': json['shots'],
        'hits': json['hits'],
        'frags': json['frags'],
        'capturePoints': json['capture_points'],
        'droppedCapturePoints': json['dropped_capture_points'],
        'hitsPercents': json['hits_percents'],
        'draws': json['draws'],
        'battleAvgXp': json['battle_avg_xp'],
        'stunNumber': json['stun_number'],
        'battlesOnStunningVehicles': json['battles_on_stunning_vehicles'],
        'stunAssistedDamage': json['stun_assisted_damage'],
        'trackAssistedDamage': json['track_assisted_damage'],
        'radioAssistedDamage': json['radio_assisted_damage'],
        'maxFrags': json['max_frags'],
        'maxXp': json['max_xp'],
        'maxDamage': json['max_damage'],
    };
}

export function TanksStatsValueItemTeamToJSON(json: any): TanksStatsValueItemTeam {
    return TanksStatsValueItemTeamToJSONTyped(json, false);
}

export function TanksStatsValueItemTeamToJSONTyped(value?: TanksStatsValueItemTeam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'battles': value['battles'],
        'wins': value['wins'],
        'xp': value['xp'],
        'losses': value['losses'],
        'survived_battles': value['survivedBattles'],
        'damage_received': value['damageReceived'],
        'damage_dealt': value['damageDealt'],
        'spotted': value['spotted'],
        'shots': value['shots'],
        'hits': value['hits'],
        'frags': value['frags'],
        'capture_points': value['capturePoints'],
        'dropped_capture_points': value['droppedCapturePoints'],
        'hits_percents': value['hitsPercents'],
        'draws': value['draws'],
        'battle_avg_xp': value['battleAvgXp'],
        'stun_number': value['stunNumber'],
        'battles_on_stunning_vehicles': value['battlesOnStunningVehicles'],
        'stun_assisted_damage': value['stunAssistedDamage'],
        'track_assisted_damage': value['trackAssistedDamage'],
        'radio_assisted_damage': value['radioAssistedDamage'],
        'max_frags': value['maxFrags'],
        'max_xp': value['maxXp'],
        'max_damage': value['maxDamage'],
    };
}

